window.FER_CONFIG={
  whatsappNumber:'56964133598',
  whatsappCatalog:'https://wa.me/c/56964133598',
  instagram:'https://www.instagram.com/fer_accesorioss_/'
};

window.FER_BRAND={
  name:'FER',
  descriptor:'accesorios',
  palette:{
    wine:'#6e3242',
    rose:'#b45d70',
    blush:'#f0c9cf',
    ivory:'#fffaf7',
    ink:'#2a1d22'
  }
};

(function loadBrand(){
  const link=document.createElement('link');
  link.rel='stylesheet';
  link.href='brand.css?v=20260907-brand';
  document.head.appendChild(link);
})();

window.FER_PRODUCTS=[
  {
    code:"FER-001",
    name:"Collar corazón",
    image:"assets/productos/whatsapp-auto/FER-001.jpg",
    images:["assets/productos/whatsapp-auto/FER-001.jpg", "assets/productos/whatsapp-auto/FER-001-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:true,
    order:1
  },
  {
    code:"FER-002",
    name:"Aritos de corazón Chileno",
    image:"assets/productos/whatsapp-auto/FER-002.jpg",
    images:["assets/productos/whatsapp-auto/FER-002.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:true,
    order:2
  },
  {
    code:"FER-003",
    name:"Traba dieciochera",
    image:"assets/productos/whatsapp-auto/FER-003.jpg",
    images:["assets/productos/whatsapp-auto/FER-003.jpg", "assets/productos/whatsapp-auto/FER-003-02.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:true,
    order:3
  },
  {
    code:"FER-004",
    name:"Aros Copihue",
    image:"assets/productos/whatsapp-auto/FER-004.jpg",
    images:["assets/productos/whatsapp-auto/FER-004.jpg", "assets/productos/whatsapp-auto/FER-004-02.jpg", "assets/productos/whatsapp-auto/FER-004-03.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:true,
    order:4
  },
  {
    code:"FER-005",
    name:"Argolla abejita y flores",
    image:"assets/productos/whatsapp-auto/FER-005.jpg",
    images:["assets/productos/whatsapp-auto/FER-005.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:true,
    order:5
  },
  {
    code:"FER-006",
    name:"Aros Rosca",
    image:"assets/productos/whatsapp-auto/FER-006.jpg",
    images:["assets/productos/whatsapp-auto/FER-006.jpg", "assets/productos/whatsapp-auto/FER-006-02.jpg", "assets/productos/whatsapp-auto/FER-006-03.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:true,
    order:6
  },
  {
    code:"FER-007",
    name:"Aros flor con piedra",
    image:"assets/productos/whatsapp-auto/FER-007.jpg",
    images:["assets/productos/whatsapp-auto/FER-007.jpg", "assets/productos/whatsapp-auto/FER-007-02.jpg", "assets/productos/whatsapp-auto/FER-007-03.jpg", "assets/productos/whatsapp-auto/FER-007-04.jpg", "assets/productos/whatsapp-auto/FER-007-05.jpg", "assets/productos/whatsapp-auto/FER-007-06.jpg", "assets/productos/whatsapp-auto/FER-007-07.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:7
  },
  {
    code:"FER-008",
    name:"Aros argollas",
    image:"assets/productos/whatsapp-auto/FER-008.jpg",
    images:["assets/productos/whatsapp-auto/FER-008.jpg", "assets/productos/whatsapp-auto/FER-008-02.jpg", "assets/productos/whatsapp-auto/FER-008-03.jpg", "assets/productos/whatsapp-auto/FER-008-04.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:8
  },
  {
    code:"FER-009",
    name:"Pulsera roja",
    image:"assets/productos/whatsapp-auto/FER-009.jpg",
    images:["assets/productos/whatsapp-auto/FER-009.jpg", "assets/productos/whatsapp-auto/FER-009-02.jpg"],
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:9
  },
  {
    code:"FER-010",
    name:"Denario",
    image:"assets/productos/whatsapp-auto/FER-010.jpg",
    images:["assets/productos/whatsapp-auto/FER-010.jpg", "assets/productos/whatsapp-auto/FER-010-02.jpg", "assets/productos/whatsapp-auto/FER-010-03.jpg", "assets/productos/whatsapp-auto/FER-010-04.jpg", "assets/productos/whatsapp-auto/FER-010-05.jpg", "assets/productos/whatsapp-auto/FER-010-06.jpg", "assets/productos/whatsapp-auto/FER-010-07.jpg"],
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:10
  },
  {
    code:"FER-011",
    name:"Pulsera niños",
    image:"assets/productos/whatsapp-auto/FER-011.jpg",
    images:["assets/productos/whatsapp-auto/FER-011.jpg", "assets/productos/whatsapp-auto/FER-011-02.jpg", "assets/productos/whatsapp-auto/FER-011-03.jpg", "assets/productos/whatsapp-auto/FER-011-04.jpg", "assets/productos/whatsapp-auto/FER-011-05.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:11
  },
  {
    code:"FER-012",
    name:"Aros conchita",
    image:"assets/productos/whatsapp-auto/FER-012.jpg",
    images:["assets/productos/whatsapp-auto/FER-012.jpg", "assets/productos/whatsapp-auto/FER-012-02.jpg", "assets/productos/whatsapp-auto/FER-012-03.jpg", "assets/productos/whatsapp-auto/FER-012-04.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:12
  },
  {
    code:"FER-013",
    name:"Aros doble corazón",
    image:"assets/productos/whatsapp-auto/FER-013.jpg",
    images:["assets/productos/whatsapp-auto/FER-013.jpg", "assets/productos/whatsapp-auto/FER-013-02.jpg", "assets/productos/whatsapp-auto/FER-013-03.jpg", "assets/productos/whatsapp-auto/FER-013-04.jpg", "assets/productos/whatsapp-auto/FER-013-05.jpg", "assets/productos/whatsapp-auto/FER-013-06.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:13
  },
  {
    code:"FER-014",
    name:"Aros estrellita",
    image:"assets/productos/whatsapp-auto/FER-014.jpg",
    images:["assets/productos/whatsapp-auto/FER-014.jpg", "assets/productos/whatsapp-auto/FER-014-02.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:14
  },
  {
    code:"FER-015",
    name:"Rosario",
    image:"assets/productos/whatsapp-auto/FER-015.jpg",
    images:["assets/productos/whatsapp-auto/FER-015.jpg"],
    category:'Accesorios',
    price:18000,
    available:null,
    isNew:false,
    order:15
  },
  {
    code:"FER-016",
    name:"Collar medallón",
    image:"assets/productos/whatsapp-auto/FER-016.jpg",
    images:["assets/productos/whatsapp-auto/FER-016.jpg", "assets/productos/whatsapp-auto/FER-016-02.jpg"],
    category:'Accesorios',
    price:20000,
    available:null,
    isNew:false,
    order:16
  },
  {
    code:"FER-017",
    name:"Conjunto corazones",
    image:"assets/productos/whatsapp-auto/FER-017.jpg",
    images:["assets/productos/whatsapp-auto/FER-017.jpg"],
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:17
  },
  {
    code:"FER-018",
    name:"Conjunto corazón",
    image:"assets/productos/whatsapp-auto/FER-018.jpg",
    images:["assets/productos/whatsapp-auto/FER-018.jpg", "assets/productos/whatsapp-auto/FER-018-02.jpg"],
    category:'Accesorios',
    price:20000,
    available:null,
    isNew:false,
    order:18
  },
  {
    code:"FER-019",
    name:"Conjunto flor",
    image:"assets/productos/whatsapp-auto/FER-019.jpg",
    images:["assets/productos/whatsapp-auto/FER-019.jpg", "assets/productos/whatsapp-auto/FER-019-02.jpg", "assets/productos/whatsapp-auto/FER-019-03.jpg", "assets/productos/whatsapp-auto/FER-019-04.jpg"],
    category:'Accesorios',
    price:22000,
    available:null,
    isNew:false,
    order:19
  },
  {
    code:"FER-020",
    name:"Anillo circular",
    image:"assets/productos/whatsapp-auto/FER-020.jpg",
    images:["assets/productos/whatsapp-auto/FER-020.jpg", "assets/productos/whatsapp-auto/FER-020-02.jpg", "assets/productos/whatsapp-auto/FER-020-03.jpg", "assets/productos/whatsapp-auto/FER-020-04.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:20
  },
  {
    code:"FER-021",
    name:"Anillo Corazón",
    image:"assets/productos/whatsapp-auto/FER-021.jpg",
    images:["assets/productos/whatsapp-auto/FER-021.jpg", "assets/productos/whatsapp-auto/FER-021-02.jpg", "assets/productos/whatsapp-auto/FER-021-03.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:21
  },
  {
    code:"FER-022",
    name:"Anillo Flor",
    image:"assets/productos/whatsapp-auto/FER-022.jpg",
    images:["assets/productos/whatsapp-auto/FER-022.jpg", "assets/productos/whatsapp-auto/FER-022-02.jpg", "assets/productos/whatsapp-auto/FER-022-03.jpg", "assets/productos/whatsapp-auto/FER-022-04.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:22
  },
  {
    code:"FER-023",
    name:"Lazos para el cabello",
    image:"assets/productos/whatsapp-auto/FER-023.jpg",
    images:["assets/productos/whatsapp-auto/FER-023.jpg", "assets/productos/whatsapp-auto/FER-023-02.jpg", "assets/productos/whatsapp-auto/FER-023-03.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:23
  },
  {
    code:"FER-024",
    name:"Traba media luna",
    image:"assets/productos/whatsapp-auto/FER-024.jpg",
    images:["assets/productos/whatsapp-auto/FER-024.jpg", "assets/productos/whatsapp-auto/FER-024-02.jpg", "assets/productos/whatsapp-auto/FER-024-03.jpg", "assets/productos/whatsapp-auto/FER-024-04.jpg", "assets/productos/whatsapp-auto/FER-024-05.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:24
  },
  {
    code:"FER-025",
    name:"Scrunchies",
    image:"assets/productos/whatsapp-auto/FER-025.jpg",
    images:["assets/productos/whatsapp-auto/FER-025.jpg", "assets/productos/whatsapp-auto/FER-025-02.jpg", "assets/productos/whatsapp-auto/FER-025-03.jpg", "assets/productos/whatsapp-auto/FER-025-04.jpg", "assets/productos/whatsapp-auto/FER-025-05.jpg", "assets/productos/whatsapp-auto/FER-025-06.jpg", "assets/productos/whatsapp-auto/FER-025-07.jpg", "assets/productos/whatsapp-auto/FER-025-08.jpg", "assets/productos/whatsapp-auto/FER-025-09.jpg"],
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:25
  },
  {
    code:"FER-026",
    name:"Aritos Brilli",
    image:"assets/productos/whatsapp-auto/FER-026.jpg",
    images:["assets/productos/whatsapp-auto/FER-026.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:26
  },
  {
    code:"FER-027",
    name:"Aros palta",
    image:"assets/productos/whatsapp-auto/FER-027.jpg",
    images:["assets/productos/whatsapp-auto/FER-027.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:27
  },
  {
    code:"FER-028",
    name:"Aros flores",
    image:"assets/productos/whatsapp-auto/FER-028.jpg",
    images:["assets/productos/whatsapp-auto/FER-028.jpg", "assets/productos/whatsapp-auto/FER-028-02.jpg", "assets/productos/whatsapp-auto/FER-028-03.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:28
  },
  {
    code:"FER-029",
    name:"Posavasos rectangulares",
    image:"assets/productos/whatsapp-auto/FER-029.jpg",
    images:["assets/productos/whatsapp-auto/FER-029.jpg", "assets/productos/whatsapp-auto/FER-029-02.jpg", "assets/productos/whatsapp-auto/FER-029-03.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:29
  },
  {
    code:"FER-030",
    name:"Posavasos",
    image:"assets/productos/whatsapp-auto/FER-030.jpg",
    images:["assets/productos/whatsapp-auto/FER-030.jpg", "assets/productos/whatsapp-auto/FER-030-02.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:30
  },
  {
    code:"FER-031",
    name:"Aros de girasol",
    image:"assets/productos/whatsapp-auto/FER-031.jpg",
    images:["assets/productos/whatsapp-auto/FER-031.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:31
  },
  {
    code:"FER-032",
    name:"Aros rosa",
    image:"assets/productos/whatsapp-auto/FER-032.jpg",
    images:["assets/productos/whatsapp-auto/FER-032.jpg", "assets/productos/whatsapp-auto/FER-032-02.jpg", "assets/productos/whatsapp-auto/FER-032-03.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:32
  },
  {
    code:"FER-033",
    name:"Aros Mandalas monocrómaticos",
    image:"assets/productos/whatsapp-auto/FER-033.jpg",
    images:["assets/productos/whatsapp-auto/FER-033.jpg", "assets/productos/whatsapp-auto/FER-033-02.jpg", "assets/productos/whatsapp-auto/FER-033-03.jpg"],
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:33
  },
  {
    code:"FER-034",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-034.jpg",
    images:["assets/productos/whatsapp-auto/FER-034.jpg", "assets/productos/whatsapp-auto/FER-034-02.jpg"],
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:34
  },
  {
    code:"FER-035",
    name:"Aros flores pequeñas",
    image:"assets/productos/whatsapp-auto/FER-035.jpg",
    images:["assets/productos/whatsapp-auto/FER-035.jpg", "assets/productos/whatsapp-auto/FER-035-02.jpg", "assets/productos/whatsapp-auto/FER-035-03.jpg", "assets/productos/whatsapp-auto/FER-035-04.jpg", "assets/productos/whatsapp-auto/FER-035-05.jpg"],
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:35
  },
  {
    code:"FER-036",
    name:"Aritos de piedra natural",
    image:"assets/productos/whatsapp-auto/FER-036.jpg",
    images:["assets/productos/whatsapp-auto/FER-036.jpg", "assets/productos/whatsapp-auto/FER-036-02.jpg", "assets/productos/whatsapp-auto/FER-036-03.jpg", "assets/productos/whatsapp-auto/FER-036-04.jpg", "assets/productos/whatsapp-auto/FER-036-05.jpg", "assets/productos/whatsapp-auto/FER-036-06.jpg", "assets/productos/whatsapp-auto/FER-036-07.jpg"],
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:36
  },
  {
    code:"FER-037",
    name:"Pulsera mano de Fátima",
    image:"assets/productos/whatsapp-auto/FER-037.jpg",
    images:["assets/productos/whatsapp-auto/FER-037.jpg", "assets/productos/whatsapp-auto/FER-037-02.jpg"],
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:37
  },
  {
    code:"FER-038",
    name:"Bambas",
    image:"assets/productos/whatsapp-auto/FER-038.jpg",
    images:["assets/productos/whatsapp-auto/FER-038.jpg", "assets/productos/whatsapp-auto/FER-038-02.jpg", "assets/productos/whatsapp-auto/FER-038-03.jpg", "assets/productos/whatsapp-auto/FER-038-04.jpg", "assets/productos/whatsapp-auto/FER-038-05.jpg", "assets/productos/whatsapp-auto/FER-038-06.jpg", "assets/productos/whatsapp-auto/FER-038-07.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:38
  },
  {
    code:"FER-039",
    name:"Girasoles",
    image:"assets/productos/whatsapp-auto/FER-039.jpg",
    images:["assets/productos/whatsapp-auto/FER-039.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:39
  },
  {
    code:"FER-040",
    name:"Pulsera árbol de la vida",
    image:"assets/productos/whatsapp-auto/FER-040.jpg",
    images:["assets/productos/whatsapp-auto/FER-040.jpg"],
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:40
  },
  {
    code:"FER-041",
    name:"Aros ala de ángel",
    image:"assets/productos/whatsapp-auto/FER-041.jpg",
    images:["assets/productos/whatsapp-auto/FER-041.jpg"],
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:41
  },
  {
    code:"FER-042",
    name:"Aros corazones multicolor",
    image:"assets/productos/whatsapp-auto/FER-042.jpg",
    images:["assets/productos/whatsapp-auto/FER-042.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:42
  },
  {
    code:"FER-043",
    name:"Aritos",
    image:"assets/productos/whatsapp-auto/FER-043.jpg",
    images:["assets/productos/whatsapp-auto/FER-043.jpg", "assets/productos/whatsapp-auto/FER-043-02.jpg", "assets/productos/whatsapp-auto/FER-043-03.jpg", "assets/productos/whatsapp-auto/FER-043-04.jpg", "assets/productos/whatsapp-auto/FER-043-05.jpg"],
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:43
  },
  {
    code:"FER-044",
    name:"Girasoles pequeños",
    image:"assets/productos/whatsapp-auto/FER-044.jpg",
    images:["assets/productos/whatsapp-auto/FER-044.jpg", "assets/productos/whatsapp-auto/FER-044-02.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:44
  },
  {
    code:"FER-045",
    name:"Collar circular",
    image:"assets/productos/whatsapp-auto/FER-045.jpg",
    images:["assets/productos/whatsapp-auto/FER-045.jpg", "assets/productos/whatsapp-auto/FER-045-02.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:45
  },
  {
    code:"FER-046",
    name:"Aros Monsteras",
    image:"assets/productos/whatsapp-auto/FER-046.jpg",
    images:["assets/productos/whatsapp-auto/FER-046.jpg", "assets/productos/whatsapp-auto/FER-046-02.jpg", "assets/productos/whatsapp-auto/FER-046-03.jpg", "assets/productos/whatsapp-auto/FER-046-04.jpg"],
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:46
  },
  {
    code:"FER-047",
    name:"Aros Abanicos",
    image:"assets/productos/whatsapp-auto/FER-047.jpg",
    images:["assets/productos/whatsapp-auto/FER-047.jpg", "assets/productos/whatsapp-auto/FER-047-02.jpg", "assets/productos/whatsapp-auto/FER-047-03.jpg", "assets/productos/whatsapp-auto/FER-047-04.jpg", "assets/productos/whatsapp-auto/FER-047-05.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:47
  },
  {
    code:"FER-048",
    name:"Aros Flor",
    image:"assets/productos/whatsapp-auto/FER-048.jpg",
    images:["assets/productos/whatsapp-auto/FER-048.jpg", "assets/productos/whatsapp-auto/FER-048-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:48
  },
  {
    code:"FER-049",
    name:"Argollas girasol",
    image:"assets/productos/whatsapp-auto/FER-049.jpg",
    images:["assets/productos/whatsapp-auto/FER-049.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:49
  },
  {
    code:"FER-050",
    name:"Aros atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-050.jpg",
    images:["assets/productos/whatsapp-auto/FER-050.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:50
  },
  {
    code:"FER-051",
    name:"Aros de Colibríes",
    image:"assets/productos/whatsapp-auto/FER-051.jpg",
    images:["assets/productos/whatsapp-auto/FER-051.jpg", "assets/productos/whatsapp-auto/FER-051-02.jpg", "assets/productos/whatsapp-auto/FER-051-03.jpg", "assets/productos/whatsapp-auto/FER-051-04.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:51
  },
  {
    code:"FER-052",
    name:"Aros soutache",
    image:"assets/productos/whatsapp-auto/FER-052.jpg",
    images:["assets/productos/whatsapp-auto/FER-052.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:52
  },
  {
    code:"FER-053",
    name:"Cangrejitos",
    image:"assets/productos/whatsapp-auto/FER-053.jpg",
    images:["assets/productos/whatsapp-auto/FER-053.jpg", "assets/productos/whatsapp-auto/FER-053-02.jpg", "assets/productos/whatsapp-auto/FER-053-03.jpg"],
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:53
  },
  {
    code:"FER-054",
    name:"Pulsera dije",
    image:"assets/productos/whatsapp-auto/FER-054.jpg",
    images:["assets/productos/whatsapp-auto/FER-054.jpg", "assets/productos/whatsapp-auto/FER-054-02.jpg", "assets/productos/whatsapp-auto/FER-054-03.jpg", "assets/productos/whatsapp-auto/FER-054-04.jpg", "assets/productos/whatsapp-auto/FER-054-05.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:54
  },
  {
    code:"FER-055",
    name:"Conjunto circular",
    image:"assets/productos/whatsapp-auto/FER-055.jpg",
    images:["assets/productos/whatsapp-auto/FER-055.jpg", "assets/productos/whatsapp-auto/FER-055-02.jpg", "assets/productos/whatsapp-auto/FER-055-03.jpg"],
    category:'Accesorios',
    price:19000,
    available:null,
    isNew:false,
    order:55
  },
  {
    code:"FER-056",
    name:"Aros flor con piedra",
    image:"assets/productos/whatsapp-auto/FER-056.jpg",
    images:["assets/productos/whatsapp-auto/FER-056.jpg", "assets/productos/whatsapp-auto/FER-056-02.jpg", "assets/productos/whatsapp-auto/FER-056-03.jpg", "assets/productos/whatsapp-auto/FER-056-04.jpg", "assets/productos/whatsapp-auto/FER-056-05.jpg", "assets/productos/whatsapp-auto/FER-056-06.jpg", "assets/productos/whatsapp-auto/FER-056-07.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:56
  },
  {
    code:"FER-057",
    name:"Aros Lilium",
    image:"assets/productos/whatsapp-auto/FER-057.jpg",
    images:["assets/productos/whatsapp-auto/FER-057.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:57
  },
  {
    code:"FER-058",
    name:"Scrunchies",
    image:"assets/productos/whatsapp-auto/FER-058.jpg",
    images:["assets/productos/whatsapp-auto/FER-058.jpg", "assets/productos/whatsapp-auto/FER-058-02.jpg", "assets/productos/whatsapp-auto/FER-058-03.jpg", "assets/productos/whatsapp-auto/FER-058-04.jpg", "assets/productos/whatsapp-auto/FER-058-05.jpg", "assets/productos/whatsapp-auto/FER-058-06.jpg", "assets/productos/whatsapp-auto/FER-058-07.jpg", "assets/productos/whatsapp-auto/FER-058-08.jpg", "assets/productos/whatsapp-auto/FER-058-09.jpg", "assets/productos/whatsapp-auto/FER-058-10.jpg"],
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:58
  },
  {
    code:"FER-059",
    name:"Aros flor",
    image:"assets/productos/whatsapp-auto/FER-059.jpg",
    images:["assets/productos/whatsapp-auto/FER-059.jpg", "assets/productos/whatsapp-auto/FER-059-02.jpg", "assets/productos/whatsapp-auto/FER-059-03.jpg", "assets/productos/whatsapp-auto/FER-059-04.jpg"],
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:59
  },
  {
    code:"FER-060",
    name:"Pulsera chip natural",
    image:"assets/productos/whatsapp-auto/FER-060.jpg",
    images:["assets/productos/whatsapp-auto/FER-060.jpg", "assets/productos/whatsapp-auto/FER-060-02.jpg", "assets/productos/whatsapp-auto/FER-060-03.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:60
  },
  {
    code:"FER-061",
    name:"Aritos Lina",
    image:"assets/productos/whatsapp-auto/FER-061.jpg",
    images:["assets/productos/whatsapp-auto/FER-061.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:61
  },
  {
    code:"FER-062",
    name:"Aros Rombo",
    image:"assets/productos/whatsapp-auto/FER-062.jpg",
    images:["assets/productos/whatsapp-auto/FER-062.jpg", "assets/productos/whatsapp-auto/FER-062-02.jpg", "assets/productos/whatsapp-auto/FER-062-03.jpg", "assets/productos/whatsapp-auto/FER-062-04.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:62
  },
  {
    code:"FER-063",
    name:"Aros piedra natural",
    image:"assets/productos/whatsapp-auto/FER-063.jpg",
    images:["assets/productos/whatsapp-auto/FER-063.jpg", "assets/productos/whatsapp-auto/FER-063-02.jpg", "assets/productos/whatsapp-auto/FER-063-03.jpg", "assets/productos/whatsapp-auto/FER-063-04.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:63
  },
  {
    code:"FER-064",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-064.jpg",
    images:["assets/productos/whatsapp-auto/FER-064.jpg", "assets/productos/whatsapp-auto/FER-064-02.jpg", "assets/productos/whatsapp-auto/FER-064-03.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:64
  },
  {
    code:"FER-065",
    name:"Argollas",
    image:"assets/productos/whatsapp-auto/FER-065.jpg",
    images:["assets/productos/whatsapp-auto/FER-065.jpg", "assets/productos/whatsapp-auto/FER-065-02.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:65
  },
  {
    code:"FER-066",
    name:"Aros mandala",
    image:"assets/productos/whatsapp-auto/FER-066.jpg",
    images:["assets/productos/whatsapp-auto/FER-066.jpg", "assets/productos/whatsapp-auto/FER-066-02.jpg"],
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:66
  },
  {
    code:"FER-067",
    name:"Collar atrapasueño",
    image:"assets/productos/whatsapp-auto/FER-067.jpg",
    images:["assets/productos/whatsapp-auto/FER-067.jpg", "assets/productos/whatsapp-auto/FER-067-02.jpg", "assets/productos/whatsapp-auto/FER-067-03.jpg", "assets/productos/whatsapp-auto/FER-067-04.jpg", "assets/productos/whatsapp-auto/FER-067-05.jpg", "assets/productos/whatsapp-auto/FER-067-06.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:67
  },
  {
    code:"FER-068",
    name:"scrunchies",
    image:"assets/productos/whatsapp-auto/FER-068.jpg",
    images:["assets/productos/whatsapp-auto/FER-068.jpg", "assets/productos/whatsapp-auto/FER-068-02.jpg", "assets/productos/whatsapp-auto/FER-068-03.jpg", "assets/productos/whatsapp-auto/FER-068-04.jpg"],
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:68
  },
  {
    code:"FER-069",
    name:"Collar Dios",
    image:"assets/productos/whatsapp-auto/FER-069.jpg",
    images:["assets/productos/whatsapp-auto/FER-069.jpg", "assets/productos/whatsapp-auto/FER-069-02.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:69
  },
  {
    code:"FER-070",
    name:"Aros Medallón",
    image:"assets/productos/whatsapp-auto/FER-070.jpg",
    images:["assets/productos/whatsapp-auto/FER-070.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:70
  },
  {
    code:"FER-071",
    name:"Aros flores triples",
    image:"assets/productos/whatsapp-auto/FER-071.jpg",
    images:["assets/productos/whatsapp-auto/FER-071.jpg", "assets/productos/whatsapp-auto/FER-071-02.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:71
  },
  {
    code:"FER-072",
    name:"Pulsera triple",
    image:"assets/productos/whatsapp-auto/FER-072.jpg",
    images:["assets/productos/whatsapp-auto/FER-072.jpg", "assets/productos/whatsapp-auto/FER-072-02.jpg"],
    category:'Accesorios',
    price:5500,
    available:null,
    isNew:false,
    order:72
  },
  {
    code:"FER-073",
    name:"Aros rosas",
    image:"assets/productos/whatsapp-auto/FER-073.jpg",
    images:["assets/productos/whatsapp-auto/FER-073.jpg", "assets/productos/whatsapp-auto/FER-073-02.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:73
  },
  {
    code:"FER-074",
    name:"Aros Margaritas",
    image:"assets/productos/whatsapp-auto/FER-074.jpg",
    images:["assets/productos/whatsapp-auto/FER-074.jpg"],
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:74
  },
  {
    code:"FER-075",
    name:"Collar piedra natural",
    image:"assets/productos/whatsapp-auto/FER-075.jpg",
    images:["assets/productos/whatsapp-auto/FER-075.jpg", "assets/productos/whatsapp-auto/FER-075-02.jpg", "assets/productos/whatsapp-auto/FER-075-03.jpg", "assets/productos/whatsapp-auto/FER-075-04.jpg", "assets/productos/whatsapp-auto/FER-075-05.jpg", "assets/productos/whatsapp-auto/FER-075-06.jpg", "assets/productos/whatsapp-auto/FER-075-07.jpg", "assets/productos/whatsapp-auto/FER-075-08.jpg", "assets/productos/whatsapp-auto/FER-075-09.jpg", "assets/productos/whatsapp-auto/FER-075-10.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:75
  },
  {
    code:"FER-076",
    name:"Pulsera Ojo turco",
    image:"assets/productos/whatsapp-auto/FER-076.jpg",
    images:["assets/productos/whatsapp-auto/FER-076.jpg", "assets/productos/whatsapp-auto/FER-076-02.jpg", "assets/productos/whatsapp-auto/FER-076-03.jpg", "assets/productos/whatsapp-auto/FER-076-04.jpg", "assets/productos/whatsapp-auto/FER-076-05.jpg", "assets/productos/whatsapp-auto/FER-076-06.jpg"],
    category:'Accesorios',
    price:2500,
    available:null,
    isNew:false,
    order:76
  },
  {
    code:"FER-077",
    name:"Aros flor de durazno",
    image:"assets/productos/whatsapp-auto/FER-077.jpg",
    images:["assets/productos/whatsapp-auto/FER-077.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:77
  },
  {
    code:"FER-078",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-078.jpg",
    images:["assets/productos/whatsapp-auto/FER-078.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:78
  },
  {
    code:"FER-079",
    name:"Aros Tortuga",
    image:"assets/productos/whatsapp-auto/FER-079.jpg",
    images:["assets/productos/whatsapp-auto/FER-079.jpg", "assets/productos/whatsapp-auto/FER-079-02.jpg", "assets/productos/whatsapp-auto/FER-079-03.jpg", "assets/productos/whatsapp-auto/FER-079-04.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:79
  },
  {
    code:"FER-080",
    name:"Pulsera rosa",
    image:"assets/productos/whatsapp-auto/FER-080.jpg",
    images:["assets/productos/whatsapp-auto/FER-080.jpg", "assets/productos/whatsapp-auto/FER-080-02.jpg", "assets/productos/whatsapp-auto/FER-080-03.jpg", "assets/productos/whatsapp-auto/FER-080-04.jpg", "assets/productos/whatsapp-auto/FER-080-05.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:80
  },
  {
    code:"FER-081",
    name:"Aros Lina",
    image:"assets/productos/whatsapp-auto/FER-081.jpg",
    images:["assets/productos/whatsapp-auto/FER-081.jpg", "assets/productos/whatsapp-auto/FER-081-02.jpg", "assets/productos/whatsapp-auto/FER-081-03.jpg", "assets/productos/whatsapp-auto/FER-081-04.jpg", "assets/productos/whatsapp-auto/FER-081-05.jpg", "assets/productos/whatsapp-auto/FER-081-06.jpg", "assets/productos/whatsapp-auto/FER-081-07.jpg", "assets/productos/whatsapp-auto/FER-081-08.jpg", "assets/productos/whatsapp-auto/FER-081-09.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:81
  },
  {
    code:"FER-082",
    name:"Aros Jazmin",
    image:"assets/productos/whatsapp-auto/FER-082.jpg",
    images:["assets/productos/whatsapp-auto/FER-082.jpg", "assets/productos/whatsapp-auto/FER-082-02.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:82
  },
  {
    code:"FER-083",
    name:"Aritos de lavanda",
    image:"assets/productos/whatsapp-auto/FER-083.jpg",
    images:["assets/productos/whatsapp-auto/FER-083.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:83
  },
  {
    code:"FER-084",
    name:"Aros triple corazón",
    image:"assets/productos/whatsapp-auto/FER-084.jpg",
    images:["assets/productos/whatsapp-auto/FER-084.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:84
  },
  {
    code:"FER-085",
    name:"Aros Perla de Río",
    image:"assets/productos/whatsapp-auto/FER-085.jpg",
    images:["assets/productos/whatsapp-auto/FER-085.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:85
  },
  {
    code:"FER-086",
    name:"Margaritas",
    image:"assets/productos/whatsapp-auto/FER-086.jpg",
    images:["assets/productos/whatsapp-auto/FER-086.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:86
  },
  {
    code:"FER-087",
    name:"Conjunto rosas",
    image:"assets/productos/whatsapp-auto/FER-087.jpg",
    images:["assets/productos/whatsapp-auto/FER-087.jpg", "assets/productos/whatsapp-auto/FER-087-02.jpg", "assets/productos/whatsapp-auto/FER-087-03.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:87
  },
  {
    code:"FER-088",
    name:"Aros botón",
    image:"assets/productos/whatsapp-auto/FER-088.jpg",
    images:["assets/productos/whatsapp-auto/FER-088.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:88
  },
  {
    code:"FER-089",
    name:"Pulsera dije",
    image:"assets/productos/whatsapp-auto/FER-089.jpg",
    images:["assets/productos/whatsapp-auto/FER-089.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:89
  },
  {
    code:"FER-090",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-090.jpg",
    images:["assets/productos/whatsapp-auto/FER-090.jpg"],
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:90
  },
  {
    code:"FER-091",
    name:"Aros Luisa",
    image:"assets/productos/whatsapp-auto/FER-091.jpg",
    images:["assets/productos/whatsapp-auto/FER-091.jpg", "assets/productos/whatsapp-auto/FER-091-02.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:91
  },
  {
    code:"FER-092",
    name:"Argollas Lavanda",
    image:"assets/productos/whatsapp-auto/FER-092.jpg",
    images:["assets/productos/whatsapp-auto/FER-092.jpg", "assets/productos/whatsapp-auto/FER-092-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:92
  },
  {
    code:"FER-093",
    name:"Aros conejito",
    image:"assets/productos/whatsapp-auto/FER-093.jpg",
    images:["assets/productos/whatsapp-auto/FER-093.jpg", "assets/productos/whatsapp-auto/FER-093-02.jpg", "assets/productos/whatsapp-auto/FER-093-03.jpg", "assets/productos/whatsapp-auto/FER-093-04.jpg", "assets/productos/whatsapp-auto/FER-093-05.jpg", "assets/productos/whatsapp-auto/FER-093-06.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:93
  },
  {
    code:"FER-094",
    name:"Conjunto Piedra Natural dorado",
    image:"assets/productos/whatsapp-auto/FER-094.jpg",
    images:["assets/productos/whatsapp-auto/FER-094.jpg", "assets/productos/whatsapp-auto/FER-094-02.jpg", "assets/productos/whatsapp-auto/FER-094-03.jpg", "assets/productos/whatsapp-auto/FER-094-04.jpg", "assets/productos/whatsapp-auto/FER-094-05.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:94
  },
  {
    code:"FER-095",
    name:"Pulseras dobles",
    image:"assets/productos/whatsapp-auto/FER-095.jpg",
    images:["assets/productos/whatsapp-auto/FER-095.jpg", "assets/productos/whatsapp-auto/FER-095-02.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:95
  },
  {
    code:"FER-096",
    name:"Aros flores",
    image:"assets/productos/whatsapp-auto/FER-096.jpg",
    images:["assets/productos/whatsapp-auto/FER-096.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:96
  },
  {
    code:"FER-097",
    name:"Aros doble corazón",
    image:"assets/productos/whatsapp-auto/FER-097.jpg",
    images:["assets/productos/whatsapp-auto/FER-097.jpg"],
    category:'Accesorios',
    price:5500,
    available:null,
    isNew:false,
    order:97
  },
  {
    code:"FER-098",
    name:"Aritos soutache",
    image:"assets/productos/whatsapp-auto/FER-098.jpg",
    images:["assets/productos/whatsapp-auto/FER-098.jpg", "assets/productos/whatsapp-auto/FER-098-02.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:98
  },
  {
    code:"FER-099",
    name:"Argollitas mandalas",
    image:"assets/productos/whatsapp-auto/FER-099.jpg",
    images:["assets/productos/whatsapp-auto/FER-099.jpg", "assets/productos/whatsapp-auto/FER-099-02.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:99
  },
  {
    code:"FER-100",
    name:"Bambas",
    image:"assets/productos/whatsapp-auto/FER-100.jpg",
    images:["assets/productos/whatsapp-auto/FER-100.jpg", "assets/productos/whatsapp-auto/FER-100-02.jpg", "assets/productos/whatsapp-auto/FER-100-03.jpg", "assets/productos/whatsapp-auto/FER-100-04.jpg", "assets/productos/whatsapp-auto/FER-100-05.jpg", "assets/productos/whatsapp-auto/FER-100-06.jpg", "assets/productos/whatsapp-auto/FER-100-07.jpg", "assets/productos/whatsapp-auto/FER-100-08.jpg", "assets/productos/whatsapp-auto/FER-100-09.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:100
  },
  {
    code:"FER-101",
    name:"Aros Flor",
    image:"assets/productos/whatsapp-auto/FER-101.jpg",
    images:["assets/productos/whatsapp-auto/FER-101.jpg", "assets/productos/whatsapp-auto/FER-101-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:101
  },
  {
    code:"FER-102",
    name:"Girasoles Grandes",
    image:"assets/productos/whatsapp-auto/FER-102.jpg",
    images:["assets/productos/whatsapp-auto/FER-102.jpg", "assets/productos/whatsapp-auto/FER-102-02.jpg"],
    category:'Accesorios',
    price:15000,
    available:null,
    isNew:false,
    order:102
  },
  {
    code:"FER-103",
    name:"Aros Camino del Inca",
    image:"assets/productos/whatsapp-auto/FER-103.jpg",
    images:["assets/productos/whatsapp-auto/FER-103.jpg", "assets/productos/whatsapp-auto/FER-103-02.jpg", "assets/productos/whatsapp-auto/FER-103-03.jpg", "assets/productos/whatsapp-auto/FER-103-04.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:103
  },
  {
    code:"FER-104",
    name:"Pulsera Corazón",
    image:"assets/productos/whatsapp-auto/FER-104.jpg",
    images:["assets/productos/whatsapp-auto/FER-104.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:104
  },
  {
    code:"FER-105",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-105.jpg",
    images:["assets/productos/whatsapp-auto/FER-105.jpg", "assets/productos/whatsapp-auto/FER-105-02.jpg", "assets/productos/whatsapp-auto/FER-105-03.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:105
  },
  {
    code:"FER-106",
    name:"Pulsera ojo turco",
    image:"assets/productos/whatsapp-auto/FER-106.jpg",
    images:["assets/productos/whatsapp-auto/FER-106.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:106
  },
  {
    code:"FER-107",
    name:"Pin de corazones",
    image:"assets/productos/whatsapp-auto/FER-107.jpg",
    images:["assets/productos/whatsapp-auto/FER-107.jpg", "assets/productos/whatsapp-auto/FER-107-02.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:107
  },
  {
    code:"FER-108",
    name:"Conjunto atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-108.jpg",
    images:["assets/productos/whatsapp-auto/FER-108.jpg", "assets/productos/whatsapp-auto/FER-108-02.jpg"],
    category:'Accesorios',
    price:16000,
    available:null,
    isNew:false,
    order:108
  },
  {
    code:"FER-109",
    name:"Aros tortuga",
    image:"assets/productos/whatsapp-auto/FER-109.jpg",
    images:["assets/productos/whatsapp-auto/FER-109.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:109
  },
  {
    code:"FER-110",
    name:"Aros gota",
    image:"assets/productos/whatsapp-auto/FER-110.jpg",
    images:["assets/productos/whatsapp-auto/FER-110.jpg", "assets/productos/whatsapp-auto/FER-110-02.jpg", "assets/productos/whatsapp-auto/FER-110-03.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:110
  },
  {
    code:"FER-111",
    name:"Aros atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-111.jpg",
    images:["assets/productos/whatsapp-auto/FER-111.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:111
  },
  {
    code:"FER-112",
    name:"Aros cascadas",
    image:"assets/productos/whatsapp-auto/FER-112.jpg",
    images:["assets/productos/whatsapp-auto/FER-112.jpg", "assets/productos/whatsapp-auto/FER-112-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:112
  },
  {
    code:"FER-113",
    name:"Aros Mariposa",
    image:"assets/productos/whatsapp-auto/FER-113.jpg",
    images:["assets/productos/whatsapp-auto/FER-113.jpg"],
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:113
  },
  {
    code:"FER-114",
    name:"Argollas abeja",
    image:"assets/productos/whatsapp-auto/FER-114.jpg",
    images:["assets/productos/whatsapp-auto/FER-114.jpg", "assets/productos/whatsapp-auto/FER-114-02.jpg", "assets/productos/whatsapp-auto/FER-114-03.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:114
  },
  {
    code:"FER-115",
    name:"Conjunto Chip",
    image:"assets/productos/whatsapp-auto/FER-115.jpg",
    images:["assets/productos/whatsapp-auto/FER-115.jpg", "assets/productos/whatsapp-auto/FER-115-02.jpg", "assets/productos/whatsapp-auto/FER-115-03.jpg"],
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:115
  },
  {
    code:"FER-116",
    name:"Bamba pequeña",
    image:"assets/productos/whatsapp-auto/FER-116.jpg",
    images:["assets/productos/whatsapp-auto/FER-116.jpg", "assets/productos/whatsapp-auto/FER-116-02.jpg", "assets/productos/whatsapp-auto/FER-116-03.jpg", "assets/productos/whatsapp-auto/FER-116-04.jpg", "assets/productos/whatsapp-auto/FER-116-05.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:116
  },
  {
    code:"FER-117",
    name:"Aros media mandala",
    image:"assets/productos/whatsapp-auto/FER-117.jpg",
    images:["assets/productos/whatsapp-auto/FER-117.jpg", "assets/productos/whatsapp-auto/FER-117-02.jpg", "assets/productos/whatsapp-auto/FER-117-03.jpg", "assets/productos/whatsapp-auto/FER-117-04.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:117
  },
  {
    code:"FER-118",
    name:"Aritos Flor",
    image:"assets/productos/whatsapp-auto/FER-118.jpg",
    images:["assets/productos/whatsapp-auto/FER-118.jpg", "assets/productos/whatsapp-auto/FER-118-02.jpg", "assets/productos/whatsapp-auto/FER-118-03.jpg", "assets/productos/whatsapp-auto/FER-118-04.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:118
  },
  {
    code:"FER-119",
    name:"Bambas diciocheras",
    image:"assets/productos/whatsapp-auto/FER-119.jpg",
    images:["assets/productos/whatsapp-auto/FER-119.jpg", "assets/productos/whatsapp-auto/FER-119-02.jpg", "assets/productos/whatsapp-auto/FER-119-03.jpg", "assets/productos/whatsapp-auto/FER-119-04.jpg"],
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:119
  },
  {
    code:"FER-120",
    name:"Pulsera corazones",
    image:"assets/productos/whatsapp-auto/FER-120.jpg",
    images:["assets/productos/whatsapp-auto/FER-120.jpg", "assets/productos/whatsapp-auto/FER-120-02.jpg", "assets/productos/whatsapp-auto/FER-120-03.jpg", "assets/productos/whatsapp-auto/FER-120-04.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:120
  },
  {
    code:"FER-121",
    name:"Aros Anaís",
    image:"assets/productos/whatsapp-auto/FER-121.jpg",
    images:["assets/productos/whatsapp-auto/FER-121.jpg"],
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:121
  },
  {
    code:"FER-122",
    name:"Pulsera concha",
    image:"assets/productos/whatsapp-auto/FER-122.jpg",
    images:["assets/productos/whatsapp-auto/FER-122.jpg", "assets/productos/whatsapp-auto/FER-122-02.jpg"],
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:122
  },
  {
    code:"FER-123",
    name:"Aritos circulares",
    image:"assets/productos/whatsapp-auto/FER-123.jpg",
    images:["assets/productos/whatsapp-auto/FER-123.jpg", "assets/productos/whatsapp-auto/FER-123-02.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:123
  },
  {
    code:"FER-124",
    name:"Pulsera doble",
    image:"assets/productos/whatsapp-auto/FER-124.jpg",
    images:["assets/productos/whatsapp-auto/FER-124.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:124
  },
  {
    code:"FER-125",
    name:"Pulsera pareja",
    image:"assets/productos/whatsapp-auto/FER-125.jpg",
    images:["assets/productos/whatsapp-auto/FER-125.jpg", "assets/productos/whatsapp-auto/FER-125-02.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:125
  },
  {
    code:"FER-126",
    name:"Pulsera 7 chackras",
    image:"assets/productos/whatsapp-auto/FER-126.jpg",
    images:["assets/productos/whatsapp-auto/FER-126.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:126
  },
  {
    code:"FER-127",
    name:"Aros mandala",
    image:"assets/productos/whatsapp-auto/FER-127.jpg",
    images:["assets/productos/whatsapp-auto/FER-127.jpg", "assets/productos/whatsapp-auto/FER-127-02.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:127
  },
  {
    code:"FER-128",
    name:"Aros Chilco",
    image:"assets/productos/whatsapp-auto/FER-128.jpg",
    images:["assets/productos/whatsapp-auto/FER-128.jpg", "assets/productos/whatsapp-auto/FER-128-02.jpg", "assets/productos/whatsapp-auto/FER-128-03.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:128
  },
  {
    code:"FER-129",
    name:"Corazones craquelados",
    image:"assets/productos/whatsapp-auto/FER-129.jpg",
    images:["assets/productos/whatsapp-auto/FER-129.jpg", "assets/productos/whatsapp-auto/FER-129-02.jpg", "assets/productos/whatsapp-auto/FER-129-03.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:129
  },
  {
    code:"FER-130",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-130.jpg",
    images:["assets/productos/whatsapp-auto/FER-130.jpg"],
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:130
  },
  {
    code:"FER-131",
    name:"Aros Alas de ángel",
    image:"assets/productos/whatsapp-auto/FER-131.jpg",
    images:["assets/productos/whatsapp-auto/FER-131.jpg", "assets/productos/whatsapp-auto/FER-131-02.jpg", "assets/productos/whatsapp-auto/FER-131-03.jpg", "assets/productos/whatsapp-auto/FER-131-04.jpg", "assets/productos/whatsapp-auto/FER-131-05.jpg", "assets/productos/whatsapp-auto/FER-131-06.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:131
  },
  {
    code:"FER-132",
    name:"Conjunto medallón",
    image:"assets/productos/whatsapp-auto/FER-132.jpg",
    images:["assets/productos/whatsapp-auto/FER-132.jpg", "assets/productos/whatsapp-auto/FER-132-02.jpg"],
    category:'Accesorios',
    price:29000,
    available:null,
    isNew:false,
    order:132
  },
  {
    code:"FER-133",
    name:"Bamba pequeña",
    image:"assets/productos/whatsapp-auto/FER-133.jpg",
    images:["assets/productos/whatsapp-auto/FER-133.jpg", "assets/productos/whatsapp-auto/FER-133-02.jpg", "assets/productos/whatsapp-auto/FER-133-03.jpg", "assets/productos/whatsapp-auto/FER-133-04.jpg", "assets/productos/whatsapp-auto/FER-133-05.jpg", "assets/productos/whatsapp-auto/FER-133-06.jpg"],
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:133
  },
  {
    code:"FER-134",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-134.jpg",
    images:["assets/productos/whatsapp-auto/FER-134.jpg", "assets/productos/whatsapp-auto/FER-134-02.jpg", "assets/productos/whatsapp-auto/FER-134-03.jpg", "assets/productos/whatsapp-auto/FER-134-04.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:134
  },
  {
    code:"FER-135",
    name:"Pulsera ágata",
    image:"assets/productos/whatsapp-auto/FER-135.jpg",
    images:["assets/productos/whatsapp-auto/FER-135.jpg", "assets/productos/whatsapp-auto/FER-135-02.jpg"],
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:135
  },
  {
    code:"FER-136",
    name:"Aros Ema",
    image:"assets/productos/whatsapp-auto/FER-136.jpg",
    images:["assets/productos/whatsapp-auto/FER-136.jpg"],
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:136
  },
  {
    code:"FER-137",
    name:"Aros Lis",
    image:"assets/productos/whatsapp-auto/FER-137.jpg",
    images:["assets/productos/whatsapp-auto/FER-137.jpg", "assets/productos/whatsapp-auto/FER-137-02.jpg", "assets/productos/whatsapp-auto/FER-137-03.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:137
  },
  {
    code:"FER-138",
    name:"Conjunto perla de río",
    image:"assets/productos/whatsapp-auto/FER-138.jpg",
    images:["assets/productos/whatsapp-auto/FER-138.jpg"],
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:138
  },
  {
    code:"FER-139",
    name:"Aros Sara",
    image:"assets/productos/whatsapp-auto/FER-139.jpg",
    images:["assets/productos/whatsapp-auto/FER-139.jpg", "assets/productos/whatsapp-auto/FER-139-02.jpg", "assets/productos/whatsapp-auto/FER-139-03.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:139
  },
  {
    code:"FER-140",
    name:"Aros conchita",
    image:"assets/productos/whatsapp-auto/FER-140.jpg",
    images:["assets/productos/whatsapp-auto/FER-140.jpg", "assets/productos/whatsapp-auto/FER-140-02.jpg", "assets/productos/whatsapp-auto/FER-140-03.jpg", "assets/productos/whatsapp-auto/FER-140-04.jpg", "assets/productos/whatsapp-auto/FER-140-05.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:140
  },
  {
    code:"FER-141",
    name:"Pulsera",
    image:"assets/productos/whatsapp-auto/FER-141.jpg",
    images:["assets/productos/whatsapp-auto/FER-141.jpg"],
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:141
  },
  {
    code:"FER-142",
    name:"Aritos Soutache",
    image:"assets/productos/whatsapp-auto/FER-142.jpg",
    images:["assets/productos/whatsapp-auto/FER-142.jpg", "assets/productos/whatsapp-auto/FER-142-02.jpg", "assets/productos/whatsapp-auto/FER-142-03.jpg"],
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:142
  },
  {
    code:"FER-143",
    name:"Aros chip",
    image:"assets/productos/whatsapp-auto/FER-143.jpg",
    images:["assets/productos/whatsapp-auto/FER-143.jpg", "assets/productos/whatsapp-auto/FER-143-02.jpg", "assets/productos/whatsapp-auto/FER-143-03.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:143
  },
  {
    code:"FER-144",
    name:"Aros gota cristal",
    image:"assets/productos/whatsapp-auto/FER-144.jpg",
    images:["assets/productos/whatsapp-auto/FER-144.jpg", "assets/productos/whatsapp-auto/FER-144-02.jpg", "assets/productos/whatsapp-auto/FER-144-03.jpg", "assets/productos/whatsapp-auto/FER-144-04.jpg", "assets/productos/whatsapp-auto/FER-144-05.jpg"],
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:144
  },
  {
    code:"FER-145",
    name:"Pulsera cristales",
    image:"assets/productos/whatsapp-auto/FER-145.jpg",
    images:["assets/productos/whatsapp-auto/FER-145.jpg", "assets/productos/whatsapp-auto/FER-145-02.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:145
  },
  {
    code:"FER-146",
    name:"Aros Mandalas",
    image:"assets/productos/whatsapp-auto/FER-146.jpg",
    images:["assets/productos/whatsapp-auto/FER-146.jpg"],
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:146
  },
  {
    code:"FER-147",
    name:"Pulsera perla de río",
    image:"assets/productos/whatsapp-auto/FER-147.jpg",
    images:["assets/productos/whatsapp-auto/FER-147.jpg"],
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:147
  },
  {
    code:"FER-148",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-148.jpg",
    images:["assets/productos/whatsapp-auto/FER-148.jpg"],
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:148
  },
  {
    code:"FER-149",
    name:"Conjunto Piedra Natural plateado",
    image:"assets/productos/whatsapp-auto/FER-149.jpg",
    images:["assets/productos/whatsapp-auto/FER-149.jpg", "assets/productos/whatsapp-auto/FER-149-02.jpg", "assets/productos/whatsapp-auto/FER-149-03.jpg", "assets/productos/whatsapp-auto/FER-149-04.jpg"],
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:149
  },
  {
    code:"FER-150",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-150.jpg",
    images:["assets/productos/whatsapp-auto/FER-150.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:150
  },
  {
    code:"FER-151",
    name:"Pulsera San Benito",
    image:"assets/productos/whatsapp-auto/FER-151.jpg",
    images:["assets/productos/whatsapp-auto/FER-151.jpg"],
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:151
  }
];