window.FER_CONFIG={
  whatsappNumber:'56964133598',
  whatsappCatalog:'https://wa.me/c/56964133598',
  instagram:'https://www.instagram.com/fer_accesorioss_/'
};

window.FER_BRAND={
  name:'FER',
  descriptor:'accesorios',
  palette:{
    wine:'#6e3242',
    rose:'#b45d70',
    blush:'#f0c9cf',
    ivory:'#fffaf7',
    ink:'#2a1d22'
  }
};

(function loadBrand(){
  const link=document.createElement('link');
  link.rel='stylesheet';
  link.href='brand.css?v=20260907-brand';
  document.head.appendChild(link);
})();

window.FER_PRODUCTS=[
  {
    code:"FER-001",
    name:"Aros Copihue",
    image:"assets/productos/whatsapp-auto/FER-001.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:true,
    order:1
  },
  {
    code:"FER-002",
    name:"Argolla abejita y flores",
    image:"assets/productos/whatsapp-auto/FER-002.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:true,
    order:2
  },
  {
    code:"FER-003",
    name:"Aros Rosca",
    image:"assets/productos/whatsapp-auto/FER-003.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:true,
    order:3
  },
  {
    code:"FER-004",
    name:"Aritos de corazón Chileno",
    image:"assets/productos/whatsapp-auto/FER-004.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:true,
    order:4
  },
  {
    code:"FER-005",
    name:"Aros flor con piedra",
    image:"assets/productos/whatsapp-auto/FER-005.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:true,
    order:5
  },
  {
    code:"FER-006",
    name:"Aros argollas",
    image:"assets/productos/whatsapp-auto/FER-006.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:true,
    order:6
  },
  {
    code:"FER-007",
    name:"Pulsera roja",
    image:"assets/productos/whatsapp-auto/FER-007.jpg",
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:7
  },
  {
    code:"FER-008",
    name:"Denario",
    image:"assets/productos/whatsapp-auto/FER-008.jpg",
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:8
  },
  {
    code:"FER-009",
    name:"Pulsera niños",
    image:"assets/productos/whatsapp-auto/FER-009.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:9
  },
  {
    code:"FER-010",
    name:"Aros conchita",
    image:"assets/productos/whatsapp-auto/FER-010.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:10
  },
  {
    code:"FER-011",
    name:"Aros doble corazón",
    image:"assets/productos/whatsapp-auto/FER-011.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:11
  },
  {
    code:"FER-012",
    name:"Aros estrellita",
    image:"assets/productos/whatsapp-auto/FER-012.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:12
  },
  {
    code:"FER-013",
    name:"Collar corazón",
    image:"assets/productos/whatsapp-auto/FER-013.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:13
  },
  {
    code:"FER-014",
    name:"Rosario",
    image:"assets/productos/whatsapp-auto/FER-014.jpg",
    category:'Accesorios',
    price:18000,
    available:null,
    isNew:false,
    order:14
  },
  {
    code:"FER-015",
    name:"Collar medallón",
    image:"assets/productos/whatsapp-auto/FER-015.jpg",
    category:'Accesorios',
    price:20000,
    available:null,
    isNew:false,
    order:15
  },
  {
    code:"FER-016",
    name:"Conjunto corazones",
    image:"assets/productos/whatsapp-auto/FER-016.jpg",
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:16
  },
  {
    code:"FER-017",
    name:"Anillo Corazón",
    image:"assets/productos/whatsapp-auto/FER-017.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:17
  },
  {
    code:"FER-018",
    name:"Anillo Flor",
    image:"assets/productos/whatsapp-auto/FER-018.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:18
  },
  {
    code:"FER-019",
    name:"Lazos para el cabello",
    image:"assets/productos/whatsapp-auto/FER-019.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:19
  },
  {
    code:"FER-020",
    name:"Traba media luna",
    image:"assets/productos/whatsapp-auto/FER-020.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:20
  },
  {
    code:"FER-021",
    name:"Scrunchies",
    image:"assets/productos/whatsapp-auto/FER-021.jpg",
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:21
  },
  {
    code:"FER-022",
    name:"Aritos Brilli",
    image:"assets/productos/whatsapp-auto/FER-022.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:22
  },
  {
    code:"FER-023",
    name:"Aros palta",
    image:"assets/productos/whatsapp-auto/FER-023.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:23
  },
  {
    code:"FER-024",
    name:"Aros flores",
    image:"assets/productos/whatsapp-auto/FER-024.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:24
  },
  {
    code:"FER-025",
    name:"Posavasos rectangulares",
    image:"assets/productos/whatsapp-auto/FER-025.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:25
  },
  {
    code:"FER-026",
    name:"Posavasos",
    image:"assets/productos/whatsapp-auto/FER-026.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:26
  },
  {
    code:"FER-027",
    name:"Aros de girasol",
    image:"assets/productos/whatsapp-auto/FER-027.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:27
  },
  {
    code:"FER-028",
    name:"Aros rosa",
    image:"assets/productos/whatsapp-auto/FER-028.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:28
  },
  {
    code:"FER-029",
    name:"Aros Mandalas monocrómaticos",
    image:"assets/productos/whatsapp-auto/FER-029.jpg",
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:29
  },
  {
    code:"FER-030",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-030.jpg",
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:30
  },
  {
    code:"FER-031",
    name:"Aros flores pequeñas",
    image:"assets/productos/whatsapp-auto/FER-031.jpg",
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:31
  },
  {
    code:"FER-032",
    name:"Aritos de piedra natural",
    image:"assets/productos/whatsapp-auto/FER-032.jpg",
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:32
  },
  {
    code:"FER-033",
    name:"Pulsera mano de Fátima",
    image:"assets/productos/whatsapp-auto/FER-033.jpg",
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:33
  },
  {
    code:"FER-034",
    name:"Bambas",
    image:"assets/productos/whatsapp-auto/FER-034.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:34
  },
  {
    code:"FER-035",
    name:"Girasoles",
    image:"assets/productos/whatsapp-auto/FER-035.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:35
  },
  {
    code:"FER-036",
    name:"Pulsera árbol de la vida",
    image:"assets/productos/whatsapp-auto/FER-036.jpg",
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:36
  },
  {
    code:"FER-037",
    name:"Aros ala de ángel",
    image:"assets/productos/whatsapp-auto/FER-037.jpg",
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:37
  },
  {
    code:"FER-038",
    name:"Aros corazones multicolor",
    image:"assets/productos/whatsapp-auto/FER-038.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:38
  },
  {
    code:"FER-039",
    name:"Aritos",
    image:"assets/productos/whatsapp-auto/FER-039.jpg",
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:39
  },
  {
    code:"FER-040",
    name:"Girasoles pequeños",
    image:"assets/productos/whatsapp-auto/FER-040.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:40
  },
  {
    code:"FER-041",
    name:"Collar circular",
    image:"assets/productos/whatsapp-auto/FER-041.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:41
  },
  {
    code:"FER-042",
    name:"Aros Monsteras",
    image:"assets/productos/whatsapp-auto/FER-042.jpg",
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:42
  },
  {
    code:"FER-043",
    name:"Aros Abanicos",
    image:"assets/productos/whatsapp-auto/FER-043.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:43
  },
  {
    code:"FER-044",
    name:"Aros Flor",
    image:"assets/productos/whatsapp-auto/FER-044.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:44
  },
  {
    code:"FER-045",
    name:"Argollas girasol",
    image:"assets/productos/whatsapp-auto/FER-045.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:45
  },
  {
    code:"FER-046",
    name:"Aros atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-046.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:46
  },
  {
    code:"FER-047",
    name:"Aros de Colibríes",
    image:"assets/productos/whatsapp-auto/FER-047.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:47
  },
  {
    code:"FER-048",
    name:"Aros soutache",
    image:"assets/productos/whatsapp-auto/FER-048.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:48
  },
  {
    code:"FER-049",
    name:"Cangrejitos",
    image:"assets/productos/whatsapp-auto/FER-049.jpg",
    category:'Accesorios',
    price:4000,
    available:null,
    isNew:false,
    order:49
  },
  {
    code:"FER-050",
    name:"Pulsera dije",
    image:"assets/productos/whatsapp-auto/FER-050.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:50
  },
  {
    code:"FER-051",
    name:"Conjunto circular",
    image:"assets/productos/whatsapp-auto/FER-051.jpg",
    category:'Accesorios',
    price:19000,
    available:null,
    isNew:false,
    order:51
  },
  {
    code:"FER-052",
    name:"Aros flor con piedra",
    image:"assets/productos/whatsapp-auto/FER-052.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:52
  },
  {
    code:"FER-053",
    name:"Aros Lilium",
    image:"assets/productos/whatsapp-auto/FER-053.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:53
  },
  {
    code:"FER-054",
    name:"Scrunchies",
    image:"assets/productos/whatsapp-auto/FER-054.jpg",
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:54
  },
  {
    code:"FER-055",
    name:"Aros flor",
    image:"assets/productos/whatsapp-auto/FER-055.jpg",
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:55
  },
  {
    code:"FER-056",
    name:"Pulsera chip natural",
    image:"assets/productos/whatsapp-auto/FER-056.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:56
  },
  {
    code:"FER-057",
    name:"Aritos Lina",
    image:"assets/productos/whatsapp-auto/FER-057.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:57
  },
  {
    code:"FER-058",
    name:"Aros Rombo",
    image:"assets/productos/whatsapp-auto/FER-058.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:58
  },
  {
    code:"FER-059",
    name:"Aros piedra natural",
    image:"assets/productos/whatsapp-auto/FER-059.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:59
  },
  {
    code:"FER-060",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-060.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:60
  },
  {
    code:"FER-061",
    name:"Argollas",
    image:"assets/productos/whatsapp-auto/FER-061.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:61
  },
  {
    code:"FER-062",
    name:"Aros mandala",
    image:"assets/productos/whatsapp-auto/FER-062.jpg",
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:62
  },
  {
    code:"FER-063",
    name:"Traba dieciochera",
    image:"assets/productos/whatsapp-auto/FER-063.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:63
  },
  {
    code:"FER-064",
    name:"Collar atrapasueño",
    image:"assets/productos/whatsapp-auto/FER-064.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:64
  },
  {
    code:"FER-065",
    name:"scrunchies",
    image:"assets/productos/whatsapp-auto/FER-065.jpg",
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:65
  },
  {
    code:"FER-066",
    name:"Collar Dios",
    image:"assets/productos/whatsapp-auto/FER-066.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:66
  },
  {
    code:"FER-067",
    name:"Aros Medallón",
    image:"assets/productos/whatsapp-auto/FER-067.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:67
  },
  {
    code:"FER-068",
    name:"Aros flores triples",
    image:"assets/productos/whatsapp-auto/FER-068.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:68
  },
  {
    code:"FER-069",
    name:"Pulsera triple",
    image:"assets/productos/whatsapp-auto/FER-069.jpg",
    category:'Accesorios',
    price:5500,
    available:null,
    isNew:false,
    order:69
  },
  {
    code:"FER-070",
    name:"Anillo circular",
    image:"assets/productos/whatsapp-auto/FER-070.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:70
  },
  {
    code:"FER-071",
    name:"Aros rosas",
    image:"assets/productos/whatsapp-auto/FER-071.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:71
  },
  {
    code:"FER-072",
    name:"Aros Margaritas",
    image:"assets/productos/whatsapp-auto/FER-072.jpg",
    category:'Accesorios',
    price:12000,
    available:null,
    isNew:false,
    order:72
  },
  {
    code:"FER-073",
    name:"Collar piedra natural",
    image:"assets/productos/whatsapp-auto/FER-073.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:73
  },
  {
    code:"FER-074",
    name:"Pulsera Ojo turco",
    image:"assets/productos/whatsapp-auto/FER-074.jpg",
    category:'Accesorios',
    price:2500,
    available:null,
    isNew:false,
    order:74
  },
  {
    code:"FER-075",
    name:"Aros flor de durazno",
    image:"assets/productos/whatsapp-auto/FER-075.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:75
  },
  {
    code:"FER-076",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-076.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:76
  },
  {
    code:"FER-077",
    name:"Conjunto flor",
    image:"assets/productos/whatsapp-auto/FER-077.jpg",
    category:'Accesorios',
    price:22000,
    available:null,
    isNew:false,
    order:77
  },
  {
    code:"FER-078",
    name:"Aros Tortuga",
    image:"assets/productos/whatsapp-auto/FER-078.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:78
  },
  {
    code:"FER-079",
    name:"Pulsera rosa",
    image:"assets/productos/whatsapp-auto/FER-079.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:79
  },
  {
    code:"FER-080",
    name:"Aros Lina",
    image:"assets/productos/whatsapp-auto/FER-080.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:80
  },
  {
    code:"FER-081",
    name:"Aros Jazmin",
    image:"assets/productos/whatsapp-auto/FER-081.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:81
  },
  {
    code:"FER-082",
    name:"Aritos de lavanda",
    image:"assets/productos/whatsapp-auto/FER-082.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:82
  },
  {
    code:"FER-083",
    name:"Aros triple corazón",
    image:"assets/productos/whatsapp-auto/FER-083.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:83
  },
  {
    code:"FER-084",
    name:"Aros Perla de Río",
    image:"assets/productos/whatsapp-auto/FER-084.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:84
  },
  {
    code:"FER-085",
    name:"Margaritas",
    image:"assets/productos/whatsapp-auto/FER-085.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:85
  },
  {
    code:"FER-086",
    name:"Conjunto rosas",
    image:"assets/productos/whatsapp-auto/FER-086.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:86
  },
  {
    code:"FER-087",
    name:"Aros botón",
    image:"assets/productos/whatsapp-auto/FER-087.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:87
  },
  {
    code:"FER-088",
    name:"Pulsera dije",
    image:"assets/productos/whatsapp-auto/FER-088.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:88
  },
  {
    code:"FER-089",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-089.jpg",
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:89
  },
  {
    code:"FER-090",
    name:"Aros Luisa",
    image:"assets/productos/whatsapp-auto/FER-090.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:90
  },
  {
    code:"FER-091",
    name:"Argollas Lavanda",
    image:"assets/productos/whatsapp-auto/FER-091.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:91
  },
  {
    code:"FER-092",
    name:"Aros conejito",
    image:"assets/productos/whatsapp-auto/FER-092.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:92
  },
  {
    code:"FER-093",
    name:"Conjunto Piedra Natural dorado",
    image:"assets/productos/whatsapp-auto/FER-093.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:93
  },
  {
    code:"FER-094",
    name:"Pulseras dobles",
    image:"assets/productos/whatsapp-auto/FER-094.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:94
  },
  {
    code:"FER-095",
    name:"Aros flores",
    image:"assets/productos/whatsapp-auto/FER-095.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:95
  },
  {
    code:"FER-096",
    name:"Aros doble corazón",
    image:"assets/productos/whatsapp-auto/FER-096.jpg",
    category:'Accesorios',
    price:5500,
    available:null,
    isNew:false,
    order:96
  },
  {
    code:"FER-097",
    name:"Aritos soutache",
    image:"assets/productos/whatsapp-auto/FER-097.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:97
  },
  {
    code:"FER-098",
    name:"Argollitas mandalas",
    image:"assets/productos/whatsapp-auto/FER-098.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:98
  },
  {
    code:"FER-099",
    name:"Bambas",
    image:"assets/productos/whatsapp-auto/FER-099.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:99
  },
  {
    code:"FER-100",
    name:"Aros Flor",
    image:"assets/productos/whatsapp-auto/FER-100.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:100
  },
  {
    code:"FER-101",
    name:"Girasoles Grandes",
    image:"assets/productos/whatsapp-auto/FER-101.jpg",
    category:'Accesorios',
    price:15000,
    available:null,
    isNew:false,
    order:101
  },
  {
    code:"FER-102",
    name:"Aros Camino del Inca",
    image:"assets/productos/whatsapp-auto/FER-102.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:102
  },
  {
    code:"FER-103",
    name:"Pulsera Corazón",
    image:"assets/productos/whatsapp-auto/FER-103.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:103
  },
  {
    code:"FER-104",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-104.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:104
  },
  {
    code:"FER-105",
    name:"Pulsera ojo turco",
    image:"assets/productos/whatsapp-auto/FER-105.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:105
  },
  {
    code:"FER-106",
    name:"Pin de corazones",
    image:"assets/productos/whatsapp-auto/FER-106.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:106
  },
  {
    code:"FER-107",
    name:"Conjunto atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-107.jpg",
    category:'Accesorios',
    price:16000,
    available:null,
    isNew:false,
    order:107
  },
  {
    code:"FER-108",
    name:"Aros tortuga",
    image:"assets/productos/whatsapp-auto/FER-108.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:108
  },
  {
    code:"FER-109",
    name:"Aros gota",
    image:"assets/productos/whatsapp-auto/FER-109.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:109
  },
  {
    code:"FER-110",
    name:"Aros atrapasueños",
    image:"assets/productos/whatsapp-auto/FER-110.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:110
  },
  {
    code:"FER-111",
    name:"Aros cascadas",
    image:"assets/productos/whatsapp-auto/FER-111.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:111
  },
  {
    code:"FER-112",
    name:"Aros Mariposa",
    image:"assets/productos/whatsapp-auto/FER-112.jpg",
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:112
  },
  {
    code:"FER-113",
    name:"Argollas abeja",
    image:"assets/productos/whatsapp-auto/FER-113.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:113
  },
  {
    code:"FER-114",
    name:"Conjunto Chip",
    image:"assets/productos/whatsapp-auto/FER-114.jpg",
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:114
  },
  {
    code:"FER-115",
    name:"Bamba pequeña",
    image:"assets/productos/whatsapp-auto/FER-115.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:115
  },
  {
    code:"FER-116",
    name:"Aros media mandala",
    image:"assets/productos/whatsapp-auto/FER-116.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:116
  },
  {
    code:"FER-117",
    name:"Aritos Flor",
    image:"assets/productos/whatsapp-auto/FER-117.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:117
  },
  {
    code:"FER-118",
    name:"Bambas diciocheras",
    image:"assets/productos/whatsapp-auto/FER-118.jpg",
    category:'Accesorios',
    price:4500,
    available:null,
    isNew:false,
    order:118
  },
  {
    code:"FER-119",
    name:"Pulsera corazones",
    image:"assets/productos/whatsapp-auto/FER-119.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:119
  },
  {
    code:"FER-120",
    name:"Aros Anaís",
    image:"assets/productos/whatsapp-auto/FER-120.jpg",
    category:'Accesorios',
    price:6500,
    available:null,
    isNew:false,
    order:120
  },
  {
    code:"FER-121",
    name:"Pulsera concha",
    image:"assets/productos/whatsapp-auto/FER-121.jpg",
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:121
  },
  {
    code:"FER-122",
    name:"Aritos circulares",
    image:"assets/productos/whatsapp-auto/FER-122.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:122
  },
  {
    code:"FER-123",
    name:"Pulsera doble",
    image:"assets/productos/whatsapp-auto/FER-123.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:123
  },
  {
    code:"FER-124",
    name:"Conjunto corazón",
    image:"assets/productos/whatsapp-auto/FER-124.jpg",
    category:'Accesorios',
    price:20000,
    available:null,
    isNew:false,
    order:124
  },
  {
    code:"FER-125",
    name:"Pulsera pareja",
    image:"assets/productos/whatsapp-auto/FER-125.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:125
  },
  {
    code:"FER-126",
    name:"Pulsera 7 chackras",
    image:"assets/productos/whatsapp-auto/FER-126.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:126
  },
  {
    code:"FER-127",
    name:"Aros mandala",
    image:"assets/productos/whatsapp-auto/FER-127.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:127
  },
  {
    code:"FER-128",
    name:"Aros Chilco",
    image:"assets/productos/whatsapp-auto/FER-128.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:128
  },
  {
    code:"FER-129",
    name:"Corazones craquelados",
    image:"assets/productos/whatsapp-auto/FER-129.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:129
  },
  {
    code:"FER-130",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-130.jpg",
    category:'Accesorios',
    price:11000,
    available:null,
    isNew:false,
    order:130
  },
  {
    code:"FER-131",
    name:"Aros Alas de ángel",
    image:"assets/productos/whatsapp-auto/FER-131.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:131
  },
  {
    code:"FER-132",
    name:"Conjunto medallón",
    image:"assets/productos/whatsapp-auto/FER-132.jpg",
    category:'Accesorios',
    price:29000,
    available:null,
    isNew:false,
    order:132
  },
  {
    code:"FER-133",
    name:"Bamba pequeña",
    image:"assets/productos/whatsapp-auto/FER-133.jpg",
    category:'Accesorios',
    price:3500,
    available:null,
    isNew:false,
    order:133
  },
  {
    code:"FER-134",
    name:"Aros Corazón",
    image:"assets/productos/whatsapp-auto/FER-134.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:134
  },
  {
    code:"FER-135",
    name:"Pulsera ágata",
    image:"assets/productos/whatsapp-auto/FER-135.jpg",
    category:'Accesorios',
    price:3000,
    available:null,
    isNew:false,
    order:135
  },
  {
    code:"FER-136",
    name:"Aros Ema",
    image:"assets/productos/whatsapp-auto/FER-136.jpg",
    category:'Accesorios',
    price:7000,
    available:null,
    isNew:false,
    order:136
  },
  {
    code:"FER-137",
    name:"Aros Lis",
    image:"assets/productos/whatsapp-auto/FER-137.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:137
  },
  {
    code:"FER-138",
    name:"Conjunto perla de río",
    image:"assets/productos/whatsapp-auto/FER-138.jpg",
    category:'Accesorios',
    price:13000,
    available:null,
    isNew:false,
    order:138
  },
  {
    code:"FER-139",
    name:"Aros Sara",
    image:"assets/productos/whatsapp-auto/FER-139.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:139
  },
  {
    code:"FER-140",
    name:"Aros conchita",
    image:"assets/productos/whatsapp-auto/FER-140.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:140
  },
  {
    code:"FER-141",
    name:"Pulsera",
    image:"assets/productos/whatsapp-auto/FER-141.jpg",
    category:'Accesorios',
    price:2000,
    available:null,
    isNew:false,
    order:141
  },
  {
    code:"FER-142",
    name:"Aritos Soutache",
    image:"assets/productos/whatsapp-auto/FER-142.jpg",
    category:'Accesorios',
    price:6000,
    available:null,
    isNew:false,
    order:142
  },
  {
    code:"FER-143",
    name:"Aros chip",
    image:"assets/productos/whatsapp-auto/FER-143.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:143
  },
  {
    code:"FER-144",
    name:"Aros gota cristal",
    image:"assets/productos/whatsapp-auto/FER-144.jpg",
    category:'Accesorios',
    price:7500,
    available:null,
    isNew:false,
    order:144
  },
  {
    code:"FER-145",
    name:"Pulsera cristales",
    image:"assets/productos/whatsapp-auto/FER-145.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:145
  },
  {
    code:"FER-146",
    name:"Aros Mandalas",
    image:"assets/productos/whatsapp-auto/FER-146.jpg",
    category:'Accesorios',
    price:8500,
    available:null,
    isNew:false,
    order:146
  },
  {
    code:"FER-147",
    name:"Pulsera perla de río",
    image:"assets/productos/whatsapp-auto/FER-147.jpg",
    category:'Accesorios',
    price:8000,
    available:null,
    isNew:false,
    order:147
  },
  {
    code:"FER-148",
    name:"Aros corazón",
    image:"assets/productos/whatsapp-auto/FER-148.jpg",
    category:'Accesorios',
    price:9000,
    available:null,
    isNew:false,
    order:148
  },
  {
    code:"FER-149",
    name:"Conjunto Piedra Natural plateado",
    image:"assets/productos/whatsapp-auto/FER-149.jpg",
    category:'Accesorios',
    price:10000,
    available:null,
    isNew:false,
    order:149
  },
  {
    code:"FER-150",
    name:"Aros circulares",
    image:"assets/productos/whatsapp-auto/FER-150.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:150
  },
  {
    code:"FER-151",
    name:"Pulsera San Benito",
    image:"assets/productos/whatsapp-auto/FER-151.jpg",
    category:'Accesorios',
    price:5000,
    available:null,
    isNew:false,
    order:151
  }
];