const sourceProducts=(window.FER_PRODUCTS||[]).slice().sort((a,b)=>(a.order||9999)-(b.order||9999));
const config=window.FER_CONFIG||{};
const descMap=new Map();let visibleLimit=24,currentProduct=null;
const $=s=>document.querySelector(s);const money=n=>n?`$${Number(n).toLocaleString('es-CL')}`:'Consultar';
function categoryOf(p){const n=(p.name||'').toLowerCase();if(/^aros?\b|^aritos?\b|^argoll/.test(n))return 'Aros';if(/^pulsera/.test(n))return 'Pulseras';if(/^collar/.test(n))return 'Collares';if(/^anillo/.test(n))return 'Anillos';if(/^conjunto/.test(n))return 'Conjuntos';if(/scrunch|bamba|traba|lazo|cabello/.test(n))return 'Cabello';return 'Otros'}
function productUrl(code){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('producto',code);return u.toString()}
function waUrl(p){return `https://wa.me/${config.whatsappNumber||'56964133598'}?text=${encodeURIComponent(`Hola, quiero consultar por ${p.name} (${p.code}). ${productUrl(p.code)}`)}`}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
async function loadDescriptions(){try{const r=await fetch('data/catalogo-whatsapp-auto.json?v=20260914');if(!r.ok)return;const data=await r.json();data.forEach(x=>descMap.set(x.codigo,x.descripcion||''))}catch(e){}}
function description(p){return descMap.get(p.code)||''}
function escapeHtml(v){return String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function productCard(p){const d=description(p);return `<article class="card"><div class="photo" data-open="${p.code}"><span class="code-tag">${p.code}</span><img src="${p.image}" alt="${escapeHtml(p.name)}" loading="lazy" decoding="async"></div><div class="card-body"><strong class="card-title">${escapeHtml(p.name)}</strong><div class="price">${money(p.price)}</div><div class="description">${escapeHtml(d||'Consulta los detalles y disponibilidad directamente por WhatsApp.')}</div><div class="card-actions"><button class="small-btn primary" data-open="${p.code}">Ver ficha</button><button class="small-btn share" data-share="${p.code}">Compartir</button><a class="small-btn wa" href="${waUrl(p)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`}
function filteredProducts(){const q=$('#searchInput').value.trim().toLowerCase();const cat=$('#categorySelect').value;let list=sourceProducts.filter(p=>{const c=categoryOf(p);const hay=`${p.code} ${p.name} ${description(p)}`.toLowerCase();return (cat==='Todos'||c===cat)&&(!q||hay.includes(q))});const sort=$('#sortSelect').value;if(sort==='price-asc')list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));if(sort==='price-desc')list.sort((a,b)=>(b.price||0)-(a.price||0));if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));return list}
function renderCatalog(reset=false){if(reset)visibleLimit=24;const list=filteredProducts();const visible=list.slice(0,visibleLimit);$('#productGrid').innerHTML=visible.map(productCard).join('');$('#resultCount').textContent=`${list.length} diseño${list.length===1?'':'s'} encontrados`;$('#showingCount').textContent=`Mostrando ${visible.length} de ${list.length}`;$('#emptyState').style.display=list.length?'none':'block';$('#loadMore').style.display=visible.length<list.length?'inline-flex':'none';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.category===$('#categorySelect').value))}
function renderFilters(){const cats=['Todos','Aros','Pulseras','Collares','Anillos','Conjuntos','Cabello','Otros'];$('#categorySelect').innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join('');$('#chips').innerHTML=cats.map(c=>`<button class="chip${c==='Todos'?' active':''}" data-category="${c}">${c}</button>`).join('');$('#statProducts').textContent=sourceProducts.length;$('#statCategories').textContent=cats.length-1}
function renderHero(){const picks=sourceProducts.slice(0,3);$('#heroGallery').innerHTML=picks.map(p=>`<button class="hero-card" data-open="${p.code}"><img src="${p.image}" alt="${escapeHtml(p.name)}"><span class="hero-label"><b>${escapeHtml(p.name)}</b><span>${money(p.price)}</span></span></button>`).join('');const featured=sourceProducts.slice(0,3);$('#featuredGrid').innerHTML=featured.map(p=>`<button class="featured-card" data-open="${p.code}"><img src="${p.image}" alt="${escapeHtml(p.name)}" loading="lazy"><span class="featured-overlay"><span><b>${escapeHtml(p.name)}</b><span>${p.code} · ${money(p.price)}</span></span></span></button>`).join('')}
function openProduct(code,push=true){const p=sourceProducts.find(x=>x.code===code);if(!p)return;currentProduct=p;$('#modalImg').src=p.image;$('#modalImg').alt=p.name;$('#modalCode').textContent=p.code;$('#modalTitle').textContent=p.name;$('#modalPrice').textContent=money(p.price);$('#modalDescription').textContent=description(p)||'Consulta disponibilidad y detalles directamente por WhatsApp.';$('#metaCode').textContent=p.code;$('#waConsult').href=waUrl(p);$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');if(push)history.pushState({product:p.code},'',productUrl(p.code))}
function closeProduct(changeUrl=true){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');$('#modalImg').src='';if(changeUrl){const u=new URL(location.href);u.searchParams.delete('producto');history.replaceState({},'',u.pathname+u.search+u.hash)}}
async function share(p){const data={title:`Fer Accesorios · ${p.name}`,text:`Mira ${p.name} en Fer Accesorios`,url:productUrl(p.code)};if(navigator.share){try{await navigator.share(data);return}catch(e){}}try{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}catch(e){}}
function bind(){document.addEventListener('click',e=>{const op=e.target.closest('[data-open]');if(op){openProduct(op.dataset.open);return}const sh=e.target.closest('[data-share]');if(sh){const p=sourceProducts.find(x=>x.code===sh.dataset.share);if(p)share(p);return}const chip=e.target.closest('.chip');if(chip){$('#categorySelect').value=chip.dataset.category;renderCatalog(true)}});$('#searchInput').addEventListener('input',()=>renderCatalog(true));$('#categorySelect').addEventListener('change',()=>renderCatalog(true));$('#sortSelect').addEventListener('change',()=>renderCatalog(true));$('#loadMore').onclick=()=>{visibleLimit+=24;renderCatalog(false)};$('#closeModal').onclick=()=>closeProduct();$('#productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#productModal').classList.contains('open'))closeProduct()});$('#shareProduct').onclick=()=>currentProduct&&share(currentProduct);$('#copyLink').onclick=async()=>{if(!currentProduct)return;try{await navigator.clipboard.writeText(productUrl(currentProduct.code));toast('Enlace copiado')}catch(e){}};window.addEventListener('popstate',()=>{const code=new URLSearchParams(location.search).get('producto');if(code)openProduct(code,false);else closeProduct(false)})}
(async function init(){renderFilters();renderHero();bind();renderCatalog(true);await loadDescriptions();renderCatalog(false);const direct=new URLSearchParams(location.search).get('producto');if(direct)setTimeout(()=>openProduct(direct,false),80)})();