const sourceProducts=(window.FER_PRODUCTS||[]).slice().sort((a,b)=>(a.order||9999)-(b.order||9999));
const config=window.FER_CONFIG||{};
const descMap=new Map();let visibleLimit=24,currentProduct=null,currentImages=[],currentImageIndex=0;
const $=s=>document.querySelector(s);const money=n=>n?`$${Number(n).toLocaleString('es-CL')}`:'Consultar';
function categoryOf(p){const n=(p.name||'').toLowerCase();if(/^aros?\b|^aritos?\b|^argoll/.test(n))return 'Aros';if(/^pulsera/.test(n))return 'Pulseras';if(/^collar/.test(n))return 'Collares';if(/^anillo/.test(n))return 'Anillos';if(/^conjunto/.test(n))return 'Conjuntos';if(/scrunch|bamba|traba|lazo|cabello/.test(n))return 'Cabello';return 'Otros'}
function productUrl(code){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('producto',code);return u.toString()}
function waUrl(p){return `https://wa.me/${config.whatsappNumber||'56964133598'}?text=${encodeURIComponent(`Hola, quiero consultar por ${p.name} (${p.code}). ${productUrl(p.code)}`)}`}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1700)}
function escapeHtml(v){return String(v||'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function imagesOf(p){const arr=Array.isArray(p.images)?p.images.filter(Boolean):[];if(!arr.length&&p.image)arr.push(p.image);return [...new Set(arr)]}
async function loadDescriptions(){try{const r=await fetch('data/catalogo-whatsapp-auto.json?v=20260914-gallery');if(!r.ok)return;const data=await r.json();data.forEach(x=>{descMap.set(x.codigo,x.descripcion||'');const p=sourceProducts.find(y=>y.code===x.codigo);if(p&&Array.isArray(x.imagenes)&&x.imagenes.length){p.images=x.imagenes;p.image=x.imagenes[0]}})}catch(e){}}
function description(p){return descMap.get(p.code)||''}
function injectGalleryStyles(){if(document.getElementById('fer-gallery-style'))return;const s=document.createElement('style');s.id='fer-gallery-style';s.textContent=`.photo-count{position:absolute;right:10px;bottom:10px;background:rgba(42,29,34,.82);color:#fff;border-radius:999px;padding:6px 9px;font-size:9px;font-weight:900;letter-spacing:.04em;backdrop-filter:blur(8px)}.modal-image{position:relative;display:flex;align-items:center;justify-content:center;padding-bottom:74px}.modal-image>img{max-height:calc(92vh - 74px)}.gallery-arrow{position:absolute;top:50%;transform:translateY(-50%);width:44px;height:44px;border:0;border-radius:50%;background:rgba(255,250,247,.92);color:#2a1d22;font-size:26px;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.13);z-index:3}.gallery-prev{left:14px}.gallery-next{right:14px}.gallery-arrow[hidden]{display:none}.modal-thumbs{position:absolute;left:12px;right:12px;bottom:10px;display:flex;gap:7px;overflow-x:auto;padding:2px;scrollbar-width:none;z-index:4}.modal-thumbs::-webkit-scrollbar{display:none}.modal-thumb{flex:0 0 52px;width:52px;height:52px;border-radius:10px;border:2px solid transparent;padding:0;background:#fff;overflow:hidden;cursor:pointer;opacity:.72}.modal-thumb.active{border-color:#6e3242;opacity:1}.modal-thumb img{width:100%;height:100%;object-fit:cover;display:block}.gallery-counter{position:absolute;top:14px;left:14px;background:rgba(42,29,34,.78);color:#fff;padding:6px 9px;border-radius:999px;font-size:9px;font-weight:900;z-index:4}@media(max-width:520px){.modal-image{padding-bottom:64px}.modal-thumb{flex-basis:46px;width:46px;height:46px}.gallery-arrow{width:38px;height:38px;font-size:22px}.modal-image>img{max-height:calc(40vh - 64px)}}`;document.head.appendChild(s)}
function productCard(p){const d=description(p),imgs=imagesOf(p);return `<article class="card"><div class="photo" data-open="${p.code}"><span class="code-tag">${p.code}</span><img src="${imgs[0]||''}" alt="${escapeHtml(p.name)}" loading="lazy" decoding="async">${imgs.length>1?`<span class="photo-count">📷 ${imgs.length}</span>`:''}</div><div class="card-body"><strong class="card-title">${escapeHtml(p.name)}</strong><div class="price">${money(p.price)}</div><div class="description">${escapeHtml(d||'Consulta los detalles y disponibilidad directamente por WhatsApp.')}</div><div class="card-actions"><button class="small-btn primary" data-open="${p.code}">Ver ficha</button><button class="small-btn share" data-share="${p.code}">Compartir</button><a class="small-btn wa" href="${waUrl(p)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`}
function filteredProducts(){const q=$('#searchInput').value.trim().toLowerCase();const cat=$('#categorySelect').value;let list=sourceProducts.filter(p=>{const c=categoryOf(p);const hay=`${p.code} ${p.name} ${description(p)}`.toLowerCase();return (cat==='Todos'||c===cat)&&(!q||hay.includes(q))});const sort=$('#sortSelect').value;if(sort==='price-asc')list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));if(sort==='price-desc')list.sort((a,b)=>(b.price||0)-(a.price||0));if(sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));return list}
function renderCatalog(reset=false){if(reset)visibleLimit=24;const list=filteredProducts();const visible=list.slice(0,visibleLimit);$('#productGrid').innerHTML=visible.map(productCard).join('');$('#resultCount').textContent=`${list.length} diseño${list.length===1?'':'s'} encontrados`;$('#showingCount').textContent=`Mostrando ${visible.length} de ${list.length}`;$('#emptyState').style.display=list.length?'none':'block';$('#loadMore').style.display=visible.length<list.length?'inline-flex':'none';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.category===$('#categorySelect').value))}
function renderFilters(){const cats=['Todos','Aros','Pulseras','Collares','Anillos','Conjuntos','Cabello','Otros'];$('#categorySelect').innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join('');$('#chips').innerHTML=cats.map(c=>`<button class="chip${c==='Todos'?' active':''}" data-category="${c}">${c}</button>`).join('');$('#statProducts').textContent=sourceProducts.length;$('#statCategories').textContent=cats.length-1}
function renderHero(){const picks=sourceProducts.slice(0,3);$('#heroGallery').innerHTML=picks.map(p=>{const img=imagesOf(p)[0]||'';return `<button class="hero-card" data-open="${p.code}"><img src="${img}" alt="${escapeHtml(p.name)}"><span class="hero-label"><b>${escapeHtml(p.name)}</b><span>${money(p.price)}</span></span></button>`}).join('');const featured=sourceProducts.slice(0,3);$('#featuredGrid').innerHTML=featured.map(p=>{const img=imagesOf(p)[0]||'';return `<button class="featured-card" data-open="${p.code}"><img src="${img}" alt="${escapeHtml(p.name)}" loading="lazy"><span class="featured-overlay"><span><b>${escapeHtml(p.name)}</b><span>${p.code} · ${money(p.price)}</span></span></span></button>`}).join('')}
function ensureGalleryUi(){const box=document.querySelector('.modal-image');if(!box||box.querySelector('.modal-thumbs'))return;const prev=document.createElement('button');prev.type='button';prev.className='gallery-arrow gallery-prev';prev.setAttribute('aria-label','Foto anterior');prev.textContent='‹';prev.onclick=()=>setModalImage(currentImageIndex-1);const next=document.createElement('button');next.type='button';next.className='gallery-arrow gallery-next';next.setAttribute('aria-label','Foto siguiente');next.textContent='›';next.onclick=()=>setModalImage(currentImageIndex+1);const counter=document.createElement('span');counter.className='gallery-counter';const thumbs=document.createElement('div');thumbs.className='modal-thumbs';box.append(prev,next,counter,thumbs)}
function renderThumbs(){ensureGalleryUi();const thumbs=document.querySelector('.modal-thumbs');thumbs.innerHTML=currentImages.map((src,i)=>`<button type="button" class="modal-thumb${i===currentImageIndex?' active':''}" data-gallery-index="${i}" aria-label="Ver foto ${i+1}"><img src="${src}" alt=""></button>`).join('');document.querySelector('.gallery-prev').hidden=currentImages.length<=1;document.querySelector('.gallery-next').hidden=currentImages.length<=1;const counter=document.querySelector('.gallery-counter');counter.textContent=currentImages.length>1?`${currentImageIndex+1} / ${currentImages.length}`:'';counter.style.display=currentImages.length>1?'inline-block':'none'}
function setModalImage(index){if(!currentImages.length)return;currentImageIndex=(index+currentImages.length)%currentImages.length;$('#modalImg').src=currentImages[currentImageIndex];$('#modalImg').alt=`${currentProduct?.name||'Producto'} · foto ${currentImageIndex+1}`;renderThumbs();const active=document.querySelector('.modal-thumb.active');active?.scrollIntoView({block:'nearest',inline:'nearest'})}
function openProduct(code,push=true){const p=sourceProducts.find(x=>x.code===code);if(!p)return;currentProduct=p;currentImages=imagesOf(p);currentImageIndex=0;ensureGalleryUi();setModalImage(0);$('#modalCode').textContent=p.code;$('#modalTitle').textContent=p.name;$('#modalPrice').textContent=money(p.price);$('#modalDescription').textContent=description(p)||'Consulta disponibilidad y detalles directamente por WhatsApp.';$('#metaCode').textContent=p.code;$('#waConsult').href=waUrl(p);$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');if(push)history.pushState({product:p.code},'',productUrl(p.code))}
function closeProduct(changeUrl=true){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');$('#modalImg').src='';currentImages=[];currentImageIndex=0;if(changeUrl){const u=new URL(location.href);u.searchParams.delete('producto');history.replaceState({},'',u.pathname+u.search+u.hash)}}
async function share(p){const data={title:`Fer Accesorios · ${p.name}`,text:`Mira ${p.name} en Fer Accesorios`,url:productUrl(p.code)};if(navigator.share){try{await navigator.share(data);return}catch(e){}}try{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}catch(e){}}
function bind(){document.addEventListener('click',e=>{const gi=e.target.closest('[data-gallery-index]');if(gi){setModalImage(Number(gi.dataset.galleryIndex));return}const op=e.target.closest('[data-open]');if(op){openProduct(op.dataset.open);return}const sh=e.target.closest('[data-share]');if(sh){const p=sourceProducts.find(x=>x.code===sh.dataset.share);if(p)share(p);return}const chip=e.target.closest('.chip');if(chip){$('#categorySelect').value=chip.dataset.category;renderCatalog(true)}});$('#searchInput').addEventListener('input',()=>renderCatalog(true));$('#categorySelect').addEventListener('change',()=>renderCatalog(true));$('#sortSelect').addEventListener('change',()=>renderCatalog(true));$('#loadMore').onclick=()=>{visibleLimit+=24;renderCatalog(false)};$('#closeModal').onclick=()=>closeProduct();$('#productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});document.addEventListener('keydown',e=>{if(!$('#productModal').classList.contains('open'))return;if(e.key==='Escape')closeProduct();if(e.key==='ArrowLeft'&&currentImages.length>1)setModalImage(currentImageIndex-1);if(e.key==='ArrowRight'&&currentImages.length>1)setModalImage(currentImageIndex+1)});$('#shareProduct').onclick=()=>currentProduct&&share(currentProduct);$('#copyLink').onclick=async()=>{if(!currentProduct)return;try{await navigator.clipboard.writeText(productUrl(currentProduct.code));toast('Enlace copiado')}catch(e){}};window.addEventListener('popstate',()=>{const code=new URLSearchParams(location.search).get('producto');if(code)openProduct(code,false);else closeProduct(false)})}
(async function init(){injectGalleryStyles();renderFilters();bind();await loadDescriptions();renderHero();renderCatalog(true);const direct=new URLSearchParams(location.search).get('producto');if(direct)setTimeout(()=>openProduct(direct,false),80)})();