const sourceProducts=(window.FER_PRODUCTS||[]).slice().sort((a,b)=>(a.order||9999)-(b.order||9999));
const config=window.FER_CONFIG||{};
const descMap=new Map();
const state={limit:24,current:null,images:[],imageIndex:0,category:'Todos',price:'Todos',tag:'Todos',sort:'order',favorites:new Set(JSON.parse(localStorage.getItem('fer_favorites_v2')||'[]'))};
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const money=n=>n?`$${Number(n).toLocaleString('es-CL')}`:'Consultar';
const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
function escapeHtml(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function imagesOf(p){const arr=Array.isArray(p.images)?p.images.filter(Boolean):[];if(!arr.length&&p.image)arr.push(p.image);return [...new Set(arr)]}
function description(p){return descMap.get(p.code)||''}
function categoryOf(p){const n=normalize(p.name);if(/^(aros?|aritos?|argolla|argollas|argollitas)\b/.test(n))return 'Aros';if(/^pulsera/.test(n))return 'Pulseras';if(/^(collar|rosario|denario)\b/.test(n))return 'Collares';if(/^anillo/.test(n))return 'Anillos';if(/^conjunto/.test(n))return 'Conjuntos';if(/scrunch|bamba|traba|lazo|cabello/.test(n))return 'Cabello';if(/posavasos/.test(n))return 'Hogar';return 'Otros'}
function tagsOf(p){const t=normalize(`${p.name} ${description(p)}`),out=[];if(/piedra natural|lapislazuli|amatista|jade|cuarzo|agata|turquesa|ojo de tigre|jaspe/.test(t))out.push('Piedra natural');if(/macrame|tejido|soutache/.test(t))out.push('Textil');if(/acero quirurgico/.test(t))out.push('Acero quirúrgico');if(/plata/.test(t))out.push('Plata');if(/banad[oa] en oro|baño de oro|tono dorado|dorado/.test(t))out.push('Dorado');if(/cristal/.test(t))out.push('Cristales');if(/arcilla polimerica/.test(t))out.push('Arcilla');if(/hecho a mano|hecha a mano|tejid|alambre de cobre/.test(t))out.push('Hecho a mano');return [...new Set(out)]}
function availabilityOf(p){const d=description(p);let m=d.match(/(\d+)\s+(?:unidades?\s+disponibles?|disponibles?)/i);if(m)return `${m[1]} disponible${Number(m[1])===1?'':'s'}`;m=d.match(/(\d+)\s+unidades?\s+por\s+color/i);if(m)return `${m[1]} por color`;m=d.match(/(\d+)\s+unidad(?:es)?\s+de\s+cada/i);if(m)return `${m[1]} por variante`;return 'Consultar disponibilidad'}
function productUrl(code){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('producto',code);return u.toString()}
function waUrl(p){return `https://wa.me/${config.whatsappNumber||'56964133598'}?text=${encodeURIComponent(`Hola, me interesa ${p.name} · ${money(p.price)} · ${p.code}. ${productUrl(p.code)}`)}`}
function waFavoritesUrl(){const items=sourceProducts.filter(p=>state.favorites.has(p.code));const lines=items.map(p=>`• ${p.name} · ${money(p.price)} · ${p.code}`);const text=`Hola, quiero consultar por estos favoritos de Fer Accesorios:\n${lines.join('\n')}\n\nCatálogo: ${location.origin}${location.pathname}`;return `https://wa.me/${config.whatsappNumber||'56964133598'}?text=${encodeURIComponent(text)}`}
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1600)}
function saveFavorites(){localStorage.setItem('fer_favorites_v2',JSON.stringify([...state.favorites]));renderFavoriteCounts();renderFavorites();renderCatalog(false);if(state.current)syncModalFavorite()}
function toggleFavorite(code){state.favorites.has(code)?state.favorites.delete(code):state.favorites.add(code);saveFavorites();toast(state.favorites.has(code)?'Agregado a favoritos':'Quitado de favoritos')}
async function loadData(){try{const r=await fetch('data/catalogo-whatsapp-auto.json?v=20260915-store-v2',{cache:'no-store'});if(!r.ok)return;const data=await r.json();data.forEach(x=>{descMap.set(x.codigo,x.descripcion||'');const p=sourceProducts.find(y=>y.code===x.codigo);if(p&&Array.isArray(x.imagenes)&&x.imagenes.length){p.images=[...new Set(x.imagenes.filter(Boolean))];p.image=p.images[0]}})}catch(e){console.error(e)}}
function priceMatch(p){if(state.price==='Todos')return true;if(state.price==='0-5000')return p.price<=5000;if(state.price==='5001-10000')return p.price>=5001&&p.price<=10000;if(state.price==='10001-15000')return p.price>=10001&&p.price<=15000;if(state.price==='15001+')return p.price>=15001;return true}
function tagMatch(p){return state.tag==='Todos'||tagsOf(p).includes(state.tag)}
function searchable(p){return normalize([p.code,p.name,description(p),categoryOf(p),...tagsOf(p)].join(' '))}
function filteredProducts(){const q=normalize($('#searchInput')?.value||'');let list=sourceProducts.filter(p=>(state.category==='Todos'||categoryOf(p)===state.category)&&priceMatch(p)&&tagMatch(p)&&(!q||searchable(p).includes(q)));if(state.sort==='price-asc')list.sort((a,b)=>(a.price||Infinity)-(b.price||Infinity));if(state.sort==='price-desc')list.sort((a,b)=>(b.price||0)-(a.price||0));if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));return list}
function favoriteButton(p,cls='favorite-btn'){return `<button class="${cls}${state.favorites.has(p.code)?' active':''}" data-favorite="${p.code}" aria-label="${state.favorites.has(p.code)?'Quitar de':'Agregar a'} favoritos">♥</button>`}
function productCard(p){const imgs=imagesOf(p),d=description(p),cat=categoryOf(p);return `<article class="card"><div class="photo${imgs.length>1?' has-second':''}" data-open="${p.code}">${favoriteButton(p)}<span class="code-tag">${p.code}</span><img class="primary-image" src="${imgs[0]||''}" alt="${escapeHtml(p.name)}" loading="lazy" decoding="async">${imgs[1]?`<img class="secondary-image" src="${imgs[1]}" alt="" loading="lazy" decoding="async">`:''}${imgs.length>1?`<span class="photo-count">▣ ${imgs.length}</span>`:''}</div><div class="card-body"><div class="card-category">${cat}</div><strong class="card-title">${escapeHtml(p.name)}</strong><div class="price">${money(p.price)}</div><div class="description">${escapeHtml(d||'Consulta detalles y disponibilidad por WhatsApp.')}</div><div class="card-actions v2"><button class="small-btn primary" data-open="${p.code}">Ver ficha</button><a class="small-btn wa" href="${waUrl(p)}" target="_blank" rel="noopener">WhatsApp</a></div></div></article>`}
function renderCatalog(reset=false){if(reset)state.limit=24;const list=filteredProducts(),visible=list.slice(0,state.limit);$('#productGrid').innerHTML=visible.map(productCard).join('');$('#resultCount').textContent=`${list.length} diseño${list.length===1?'':'s'} encontrados`;$('#showingCount').textContent=`Mostrando ${visible.length} de ${list.length}`;$('#emptyState').style.display=list.length?'none':'block';$('#loadMore').style.display=visible.length<list.length?'inline-flex':'none';$$('.chip').forEach(x=>x.classList.toggle('active',x.dataset.category===state.category));$$('.tag-chip').forEach(x=>x.classList.toggle('active',x.dataset.tag===state.tag))}
function renderFilters(){const cats=['Todos','Aros','Pulseras','Collares','Anillos','Conjuntos','Cabello','Hogar','Otros'];$('#categorySelect').innerHTML=cats.map(c=>`<option value="${c}">${c}</option>`).join('');$('#chips').innerHTML=cats.map(c=>`<button class="chip${c==='Todos'?' active':''}" data-category="${c}">${c}</button>`).join('');const tags=['Todos','Piedra natural','Textil','Acero quirúrgico','Plata','Dorado','Cristales','Arcilla','Hecho a mano'];$('#tagSelect').innerHTML=tags.map(t=>`<option value="${t}">${t==='Todos'?'Material / estilo':t}</option>`).join('');$('#tagChips').innerHTML=tags.slice(1).map(t=>`<button class="tag-chip" data-tag="${t}">${t}</button>`).join('');$('#statProducts').textContent=sourceProducts.length;$('#statCategories').textContent=cats.length-2;renderFavoriteCounts()}
function railCard(p){const img=imagesOf(p)[0]||'';return `<article class="rail-card"><button class="rail-card-main" data-open="${p.code}" style="all:unset;display:block;cursor:pointer;width:100%"><img src="${img}" alt="${escapeHtml(p.name)}" loading="lazy"><div class="rail-card-copy"><b>${escapeHtml(p.name)}</b><span>${money(p.price)}</span></div></button>${favoriteButton(p,'rail-heart')}</article>`}
function renderCommercial(){const newer=sourceProducts.filter(p=>p.isNew).slice(0,8);const gifts=sourceProducts.filter(p=>p.price&&p.price<=10000).slice(0,10);const stones=sourceProducts.filter(p=>tagsOf(p).includes('Piedra natural')).slice(0,10);const handmade=sourceProducts.filter(p=>tagsOf(p).includes('Hecho a mano')).slice(0,10);$('#railNew').innerHTML=(newer.length?newer:sourceProducts.slice(0,8)).map(railCard).join('');$('#railGifts').innerHTML=gifts.map(railCard).join('');$('#railStones').innerHTML=stones.map(railCard).join('');$('#railHandmade').innerHTML=handmade.map(railCard).join('');const counts={Aros:sourceProducts.filter(p=>categoryOf(p)==='Aros').length,Pulseras:sourceProducts.filter(p=>categoryOf(p)==='Pulseras').length,'Piedra natural':stones.length,'Hasta $10.000':gifts.length};$('#collectionCards').innerHTML=[['Aros','Diseños para todos los estilos','category:Aros',counts.Aros],['Pulseras','Opciones para usar o regalar','category:Pulseras',counts.Pulseras],['Piedras naturales','Amatista, jade, cuarzo y más','tag:Piedra natural',counts['Piedra natural']],['Regalos hasta $10.000','Ideas por precio','price:5001-10000',counts['Hasta $10.000']]].map(([title,txt,filter,count])=>`<button class="collection-card" data-collection="${filter}"><strong>${count} diseños</strong><b>${title}</b><span>${txt}</span></button>`).join('')}
function renderHero(){const picks=sourceProducts.slice(0,3);$('#heroGallery').innerHTML=picks.map(p=>`<button class="hero-card" data-open="${p.code}"><img src="${imagesOf(p)[0]||''}" alt="${escapeHtml(p.name)}"><span class="hero-label"><b>${escapeHtml(p.name)}</b><span>${money(p.price)}</span></span></button>`).join('');const featured=sourceProducts.slice(3,6);$('#featuredGrid').innerHTML=featured.map(p=>`<button class="featured-card" data-open="${p.code}"><img src="${imagesOf(p)[0]||''}" alt="${escapeHtml(p.name)}" loading="lazy"><span class="featured-overlay"><span><b>${escapeHtml(p.name)}</b><span>${p.code} · ${money(p.price)}</span></span></span></button>`).join('')}
function renderSearchSuggestions(){const box=$('#searchSuggestions'),q=normalize($('#searchInput').value);if(q.length<2){box.classList.remove('open');box.innerHTML='';return}const matches=sourceProducts.filter(p=>searchable(p).includes(q)).slice(0,5);if(!matches.length){box.classList.remove('open');return}box.innerHTML=matches.map(p=>`<button class="suggestion" data-open="${p.code}"><img src="${imagesOf(p)[0]||''}" alt=""><b>${escapeHtml(p.name)}</b><span>${money(p.price)}</span></button>`).join('');box.classList.add('open')}
function renderFavoriteCounts(){const n=state.favorites.size;$$('[data-fav-count]').forEach(el=>el.textContent=n);$('#statFavorites').textContent=n}
function renderFavorites(){const list=$('#favoritesList'),items=sourceProducts.filter(p=>state.favorites.has(p.code));if(!list)return;if(!items.length){list.innerHTML='<div class="favorites-empty"><b>Aún no tienes favoritos</b><p>Marca el corazón en los productos que quieras comparar o consultar después.</p></div>';$('#favoritesWhatsApp').style.display='none';return}list.innerHTML=items.map(p=>`<div class="favorite-row"><button data-open="${p.code}" style="all:unset;cursor:pointer"><img src="${imagesOf(p)[0]||''}" alt="${escapeHtml(p.name)}"></button><button data-open="${p.code}" style="all:unset;cursor:pointer;text-align:left"><b>${escapeHtml(p.name)}</b><span>${money(p.price)} · ${p.code}</span></button><button class="favorite-remove" data-favorite="${p.code}" aria-label="Quitar">×</button></div>`).join('');$('#favoritesWhatsApp').style.display='inline-flex';$('#favoritesWhatsApp').href=waFavoritesUrl();$('#favoritesFootText').textContent=`${items.length} producto${items.length===1?'':'s'} seleccionado${items.length===1?'':'s'}`}
function openFavorites(){renderFavorites();$('#favoritesOverlay').classList.add('open');$('#favoritesDrawer').classList.add('open');document.body.classList.add('modal-open')}
function closeFavorites(){$('#favoritesOverlay').classList.remove('open');$('#favoritesDrawer').classList.remove('open');if(!$('#productModal').classList.contains('open'))document.body.classList.remove('modal-open')}
function ensureGalleryUi(){const box=$('.modal-image');if(!box||box.querySelector('.modal-thumbs'))return;const prev=document.createElement('button');prev.type='button';prev.className='gallery-arrow gallery-prev';prev.textContent='‹';prev.setAttribute('aria-label','Foto anterior');prev.onclick=()=>setModalImage(state.imageIndex-1);const next=document.createElement('button');next.type='button';next.className='gallery-arrow gallery-next';next.textContent='›';next.setAttribute('aria-label','Foto siguiente');next.onclick=()=>setModalImage(state.imageIndex+1);const counter=document.createElement('span');counter.className='gallery-counter';const thumbs=document.createElement('div');thumbs.className='modal-thumbs';box.append(prev,next,counter,thumbs)}
function renderThumbs(){ensureGalleryUi();const thumbs=$('.modal-thumbs');thumbs.innerHTML=state.images.map((src,i)=>`<button type="button" class="modal-thumb${i===state.imageIndex?' active':''}" data-gallery-index="${i}"><img src="${src}" alt=""></button>`).join('');$('.gallery-prev').hidden=state.images.length<=1;$('.gallery-next').hidden=state.images.length<=1;const c=$('.gallery-counter');c.textContent=state.images.length>1?`${state.imageIndex+1} / ${state.images.length}`:'';c.style.display=state.images.length>1?'inline-block':'none'}
function setModalImage(index){if(!state.images.length)return;state.imageIndex=(index+state.images.length)%state.images.length;$('#modalImg').src=state.images[state.imageIndex];$('#modalImg').alt=`${state.current?.name||'Producto'} · foto ${state.imageIndex+1}`;renderThumbs()}
function relatedProducts(p){const cat=categoryOf(p),tags=tagsOf(p);return sourceProducts.filter(x=>x.code!==p.code).map(x=>{let score=0;if(categoryOf(x)===cat)score+=5;score+=tagsOf(x).filter(t=>tags.includes(t)).length*2;score-=Math.min(3,Math.abs((x.price||0)-(p.price||0))/5000);return{x,score}}).sort((a,b)=>b.score-a.score).slice(0,4).map(o=>o.x)}
function renderRelated(p){$('#relatedGrid').innerHTML=relatedProducts(p).map(x=>`<button class="related-card" data-open="${x.code}"><img src="${imagesOf(x)[0]||''}" alt=""><span>${escapeHtml(x.name)}</span></button>`).join('')}
function syncModalFavorite(){const b=$('#modalFavorite');if(!state.current)return;b.classList.toggle('active',state.favorites.has(state.current.code));b.textContent=state.favorites.has(state.current.code)?'♥ Guardado en favoritos':'♡ Agregar a favoritos'}
function openProduct(code,push=true){const p=sourceProducts.find(x=>x.code===code);if(!p)return;closeFavorites();state.current=p;state.images=imagesOf(p);state.imageIndex=0;ensureGalleryUi();setModalImage(0);$('#modalCode').textContent=p.code;$('#modalTitle').textContent=p.name;$('#modalPrice').textContent=money(p.price);$('#modalDescription').textContent=description(p)||'Consulta disponibilidad y detalles directamente por WhatsApp.';$('#metaCode').textContent=p.code;$('#metaAvailability').textContent=availabilityOf(p);$('#modalAvailability').textContent=availabilityOf(p);$('#productTags').innerHTML=[categoryOf(p),...tagsOf(p)].map(t=>`<span class="product-tag">${t}</span>`).join('');$('#waConsult').href=waUrl(p);syncModalFavorite();renderRelated(p);$('#productModal').classList.add('open');$('#productModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');$('#searchSuggestions').classList.remove('open');if(push)history.pushState({product:p.code},'',productUrl(p.code))}
function closeProduct(changeUrl=true){$('#productModal').classList.remove('open');$('#productModal').setAttribute('aria-hidden','true');if(!$('#favoritesDrawer').classList.contains('open'))document.body.classList.remove('modal-open');$('#modalImg').src='';state.images=[];state.imageIndex=0;if(changeUrl){const u=new URL(location.href);u.searchParams.delete('producto');history.replaceState({},'',u.pathname+u.search+u.hash)}}
async function share(p){const data={title:`Fer Accesorios · ${p.name}`,text:`${p.name} · ${money(p.price)} · ${p.code}`,url:productUrl(p.code)};if(navigator.share){try{await navigator.share(data);return}catch(e){}}try{await navigator.clipboard.writeText(data.url);toast('Enlace copiado')}catch(e){}}
function applyCollection(filter){const [type,value]=filter.split(':');if(type==='category'){state.category=value;$('#categorySelect').value=value}if(type==='tag'){state.tag=value;$('#tagSelect').value=value}if(type==='price'){state.price=value;$('#priceSelect').value=value}renderCatalog(true);document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'})}
function bind(){document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){e.preventDefault();e.stopPropagation();toggleFavorite(fav.dataset.favorite);return}const gi=e.target.closest('[data-gallery-index]');if(gi){setModalImage(Number(gi.dataset.galleryIndex));return}const op=e.target.closest('[data-open]');if(op){openProduct(op.dataset.open);return}const chip=e.target.closest('.chip');if(chip){state.category=chip.dataset.category;$('#categorySelect').value=state.category;renderCatalog(true);return}const tag=e.target.closest('.tag-chip');if(tag){state.tag=state.tag===tag.dataset.tag?'Todos':tag.dataset.tag;$('#tagSelect').value=state.tag;renderCatalog(true);return}const col=e.target.closest('[data-collection]');if(col){applyCollection(col.dataset.collection);return}});$('#searchInput').addEventListener('input',()=>{renderCatalog(true);renderSearchSuggestions()});$('#searchInput').addEventListener('focus',renderSearchSuggestions);document.addEventListener('click',e=>{if(!e.target.closest('.search'))$('#searchSuggestions').classList.remove('open')});$('#categorySelect').addEventListener('change',e=>{state.category=e.target.value;renderCatalog(true)});$('#priceSelect').addEventListener('change',e=>{state.price=e.target.value;renderCatalog(true)});$('#tagSelect').addEventListener('change',e=>{state.tag=e.target.value;renderCatalog(true)});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderCatalog(true)});$('#loadMore').onclick=()=>{state.limit+=24;renderCatalog(false)};$('#favoritesNav').onclick=openFavorites;$('#favoritesFloating').onclick=openFavorites;$('#mobileFavorites').onclick=e=>{e.preventDefault();openFavorites()};$('#favoritesClose').onclick=closeFavorites;$('#favoritesOverlay').onclick=closeFavorites;$('#closeModal').onclick=()=>closeProduct();$('#productModal').addEventListener('click',e=>{if(e.target.id==='productModal')closeProduct()});$('#modalFavorite').onclick=()=>state.current&&toggleFavorite(state.current.code);$('#shareProduct').onclick=()=>state.current&&share(state.current);$('#copyLink').onclick=async()=>{if(!state.current)return;try{await navigator.clipboard.writeText(productUrl(state.current.code));toast('Enlace copiado')}catch(e){}};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if($('#favoritesDrawer').classList.contains('open'))closeFavorites();else if($('#productModal').classList.contains('open'))closeProduct()}if($('#productModal').classList.contains('open')&&state.images.length>1){if(e.key==='ArrowLeft')setModalImage(state.imageIndex-1);if(e.key==='ArrowRight')setModalImage(state.imageIndex+1)}});window.addEventListener('popstate',()=>{const code=new URLSearchParams(location.search).get('producto');if(code)openProduct(code,false);else closeProduct(false)})}
(async function init(){renderFilters();bind();await loadData();renderHero();renderCommercial();renderCatalog(true);renderFavorites();const direct=new URLSearchParams(location.search).get('producto');if(direct)setTimeout(()=>openProduct(direct,false),80)})();